### ISSUE TITLE
Generate document command does not work in subfolder document in yml format

### ISSUE THREAD

**Issue by wlzch** [doctrine/DoctrineMongoDBBundle#105]
I have a document in Acme\DemoBundle\Document\Product\Car.php which extends Acme\DemoBundle\Document\BaseProduct.php.
I'm using yml for the mapping.

when I run doctrine:mongodb:generate:documents this exception occured
[Doctrine\ODM\MongoDB\MongoDBException]  
  No mapping found for field '/xxx/testing/src/Acme/DemoBundle/Resources/config/doctrine/Car.mongodb.yml' in class 'Acme\DemoBundle\  
  Document\Car'.

It's strange. I actually put the mapping in Acme/DemoBundle/Resources/config/doctrine/product/Car.mongodb.yml, but it search in the parent folder.

NB: It works in annotation format.

**Comment by webdevilopers** [comment]
The same happens with XML but the error message is more precise:
```
No mapping file found named 'OrderCustomer.mongodb.xml' for class 'Acme\Contract\DomainModel\Order\OrderCustomer
```

"Precisely wrong"! ;)

Should I open an issue to fix the expected filename as defined by @stof to `Order.OrderCustomer.mongodb.xml`?

**Comment by malarzm** [comment]
@webdevilopers yes please. If also you'd have time and/or will to work on a PR with fix it'd be even more awesome ;)
