### ISSUE TITLE
The fields "0" were not expected

### ISSUE THREAD

**Issue by BobbySix** [doctrine/DoctrineMongoDBBundle#113]
HI,

I use Symfony 2 and the bundle DoctrineMongoDBBundle, I access the data, I write data, all going well except when I use the Field type "document" on one of my form, when i submit  I get the error: `The fields "0" were not expected`

And i get this message as many elements has been selected in the list.

The Form Type code :

```
public function buildForm(FormBuilder $builder, array $options)
{
    parent::buildForm($builder, $options);

    $builder->add('templates', 'document', array(
        'class' => 'Dofa\ManagerBundle\Document\Template',
        'multiple' => 'true',
        'expanded' => 'true',
        'property' => 'name'                    
    ));
}
```

The view : 

```
<form id="form_user_template" action="{{ path('DofaManagerBundle_user_edit_process', {'id':'4f45268b86b4484c10000000'}) }}" {{     form_enctype(formTemplate) }} method="POST" class="fos_user_profile_edit">
    {{ form_rest(formTemplate) }}
    <button class="blue-button" type="submit">Submit</button>
</form>
```

Any idea where i could come from ? it's seems that everytime i use a collection with a "ReferenceMany" annotations it doesn't work properly.

Thanks

**Comment by malarzm** [comment]
FWIW it should be working correctly now in 2016
