### ISSUE TITLE
Aggregation Framework

### ISSUE THREAD

**Issue by dgoujard** [doctrine/DoctrineMongoDBBundle#165]
Hi,

I would like to know if it's possible to use [MongoDB Aggregation Framework](http://docs.mongodb.org/manual/applications/aggregation/) It's an interesting feature and i don't know how use it on Symfony with this bundle. I'm new in Symfony dev. Otherwise, how send raw query to MongoDB?

Thank you !

**Comment by luishdez** [comment]
This issue It's a little bit old but I'm using https://github.com/f1nder/SolutionMongoAggregationBundle that has a query builder and works with doctrine, Though their query builders are not compatible …
