### ISSUE TITLE
Polymorphic reference and COLLECTION_PER_CLASS inheritance

### ISSUE THREAD

**Issue by amarisi** [doctrine/DoctrineMongoDBBundle#179]
Hello, I'm having a problem with a @ReferenceOne to the superclass of a hierarchy mapped with the COLLECTION_PER_CLASS strategy.
This is the sample code:

<pre>
/**
 * @MongoDB\Document
 */
class SingleInstanceRequest
{
    /**
     * @MongoDB\Id
     */
	private $id;

    /**
     * @MongoDB\ReferenceOne(targetDocument="Provider")
     */
    private $provider;
}
</pre>

<pre>
/**
 * @MongoDB\Document
 * @MongoDB\InheritanceType("COLLECTION_PER_CLASS")
 */
class Provider
{
    /**
     * @MongoDB\Id
     */
    protected $id;

    /**
     * Get id
     *
     * @return id $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function getProviderName()
    {
        return '';
    }
}
</pre>

<pre>
/**
 * @MongoDB\Document
 */
class Institution extends Provider
{
    /**
     * @Assert\NotBlank()
     * @MongoDB\String
     */
    private $name;

    /**
     * Set name
     *
     * @param string $name
     * @return Institution
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Get name
     *
     * @return string $name
     */
    public function getName()
    {
        return $this->name;
    }

    public function getProviderName()
    {
        return $this->getName();
    }
}
</pre>

<pre>
$institution = new Institution();
$institution->setName('foo');
$dm->persist($institution);
$dm->flush();

$request =  new SingleInstanceRequest();
$request->setProvider($institution);
$dm->persist($request);
$dm->flush();
</pre>

When I try to invoke the getProviderName method, i get the following error:

<pre>
An exception has been thrown during the rendering of a template ("The "MongoDBODMProxies\__CG__\Celsius\Celsius3Bundle\Document\Provider" document with identifier "514b4408e4b889b80f0013ab" could not be found.") in /home/agustin/workspace/Celsius3/src/Celsius/Celsius3Bundle/Resources/views/AdminOrder/show.html.twig at line 10. 
</pre>

As I understand, the document is being searched in the Provider collection instead of the Institution collection, but I don't know why. Is there something wrong with the mappings?

Thank you in advance.

**Comment by alcaeus** [comment]
This is a limitation in ODM itself: when you add targetDocument annotation to a reference it will always create a proxy for that class, unless a class discriminator was found (either a class name or defined in a discriminator_map).
