### ISSUE TITLE
Allow bundle to be configured and operate without ODM

### ISSUE THREAD

**Issue by jmikola** [doctrine/DoctrineMongoDBBundle#186]
See: @stof's comment in https://github.com/doctrine/DoctrineMongoDBBundle/pull/184#discussion_r3856315

> IMO, the config of the bundle should be splitted in 2 parts like in DoctrineBundle:
> - one part related to connections
> - one part related to the ODM and being optional for people wanting to use only the MongoDB connection directly

**Comment by alcaeus** [comment]
Closing here: since the connection part is no longer handled by `doctrine/mongodb` but rather `mongodb/mongodb` I don't think this is viable.
