### ISSUE TITLE
Yaml & Xml mapper are filename case sensitive ?

### ISSUE THREAD

**Issue by ludofleury** [doctrine/DoctrineMongoDBBundle#205]
This behavior was really surprising, since I had no problem with doctrine ORM, my mapping yml file with ODM should be case sensitive. I'm missing something ?

**Comment by malarzm** [comment]
Closing because of no follow up, also I believe there's nothing wrong in Bundle since we're not loading files in any strange way. Please feel free to reopen if the issue persists though.
