### ISSUE TITLE
Unique Constraint in reference only works with simple references 

### ISSUE THREAD

**Issue by azr** [doctrine/DoctrineMongoDBBundle#208]
Hello,
I have the  following unique constraint :

```php
...
use Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique as MongoDBUnique;
...
   /**
    * @MongoDBUnique(fields={"creator", "target"})
    */
class Poke {
...
    /**
     * @MongoDB\ReferenceOne(targetDocument="User", cascade="none")
     */
    protected $creator;

// target is also a user

```

no matter if I put ```simple=true``` to my reference the following request is executed upon validation :

```mongoDB
db.Poke.find({ "creator": "52c2b2b4110bb12c030048b7", "target": "52c2b2b4110bb12c030048b7" });
```

In the case when the reference is not a simple one more stuff is added to the target/creator fields making the validation never sending errors.

if I use @MongoDBUnique(fields={"creator_id", "target_id"}) I get the

```php
  new ConstraintDefinitionException(sprintf("The field '%s' is not mapped by Doctrine, so it cannot be validated for uniqueness.", $fieldName));
```

Thrown at my face.

Works well for the simple ref though :).

**Comment by malarzm** [comment]
Should be fixed once we merge https://github.com/doctrine/mongodb-odm/pull/1363 into ODM

**Comment by malarzm** [comment]
https://github.com/doctrine/mongodb-odm/pull/1363 has been merged, if it doesn't fix the issue please open new ticket

**Comment by christiankasse** [comment]
> Hello,
> I have the following unique constraint :
> 
> ```
> ...
> use Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique as MongoDBUnique;
> ...
>    /**
>     * @MongoDBUnique(fields={"creator", "target"})
>     */
> class Poke {
> ...
>     /**
>      * @MongoDB\ReferenceOne(targetDocument="User", cascade="none")
>      */
>     protected $creator;
> 
> // target is also a user
> ```
> 
> no matter if I put `simple=true` to my reference the following request is executed upon validation :
> 
> ```
> db.Poke.find({ "creator": "52c2b2b4110bb12c030048b7", "target": "52c2b2b4110bb12c030048b7" });
> ```
> 
> In the case when the reference is not a simple one more stuff is added to the target/creator fields making the validation never sending errors.
> 
> if I use @MongoDBUnique(fields={"creator_id", "target_id"}) I get the
> 
> ```
>   new ConstraintDefinitionException(sprintf("The field '%s' is not mapped by Doctrine, so it cannot be validated for uniqueness.", $fieldName));
> ```
> 
> Thrown at my face.
> 
> Works well for the simple ref though :).

I for me it's not work
`
/**
 * @MongoDB\Document(collection="users", repositoryClass=UserRepository::class)
 * @MongoDBUnique(fields={"email", "username","phoneNumber"})
 * @MongoDB\HasLifecycleCallbacks
 */
class User implements UserInterface
{`

**Comment by alcaeus** [comment]
@christiankasse please create a new issue instead of resurrecting an old one. When you do so, please also provide more information than just "it doesn't work": I can show you an example that does. Instead, explain what doesn't work, e.g. what error messages you are receiving.

I've also fixed your code sample - you need to fence multi-line code blocks with three backticks instead of one.
