### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by beniwtv** [doctrine/DoctrineMongoDBBundle#214]
Hi,

Using MongoDB with SSL would require passing the "ssl: true" parameter to php-mongo. However, when I specify it in the "options" part of the connection, I get:

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
Unrecognized options "ssl" under "doctrine_mongodb.connections.default.options"

How would I go about configuring this? Or am I missing something?

Best regards,
Benedikt

**Comment by manuelbcd** [comment]
Sorry for re-posting here but it would be fantastic if doctrine could support context configuration with the old MongoDB driver.

SSL is boolean right now but with the legacy driver it accepts options like "allow_self_signed" or "pemfile" as well.

I think it would be a temporary fix but will improve flexibility until doctrine2 is realeased.

**Comment by alcaeus** [comment]
No need to re-post here since we've already said we'd build it in #380.

**Comment by manuelbcd** [comment]
Yes alcaeus sorry, i'm very interested.  Thanks for your answer.
