### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by patkar** [doctrine/DoctrineMongoDBBundle#216]
The latest tag `v3.0.0-BETA5` is 10 months old. While this is no issue on its own, because it works, the [Symfony Cookbook](http://symfony.com/doc/current/cookbook/doctrine/mapping_model_classes.html) mentions a feature available `>=3.0.0` but it's only existing on dev-master.

Same issue as doctrine/DoctrineBundle#244 ;-)

**Comment by malarzm** [comment]
Closing issue since 3.0.0-BETA6 was released after tag request
