### ISSUE TITLE
PreUpdate Event not fired when update a referenceMany

### ISSUE THREAD

**Issue by Fabex** [doctrine/DoctrineMongoDBBundle#230]
Hi,
I have a weird issue with preUpdate on an event listener, I explain.
I have a first document named A.
This document A have a referenceMany to a document B and a referenceOne to a document C.

I want to do some stuff when some properties of document A are changed.
So I created a PreUpdate listener class to do my stuff.
If there is a modification on A->C my listener is called and I can do my stuff.
But if there is a modification on one of A->B (add or remove) the listener preUpdate is not called.

Here my class A
```php
/**
 * @MongoDB\Document(collection="a", repositoryClass="Acme\Bundle\AcmeBundle\Repository\ARepository")
*/
class A
{
/**
     * @var C
     * @MongoDB\ReferenceOne(targetDocument="Acme\Bundle\AcmeBundle\Document\Image", cascade={"all"})
     */
    protected $c;
/**
     * @var B[]
     * @MongoDB\ReferenceMany(targetDocument="Acme\Bundle\AcmeBundle\Document\B", cascade={"all"})
     */
    protected $bs;
}
```
Here my service definition
```yml
<service id="acme.listener.update" class="%acme.listener.update.class%">
    <tag name="doctrine_mongodb.odm.event_listener" event="preUpdate" />
</service>
```

**Comment by malarzm** [comment]
As stated before the issue is reported in ODM and shall be fixed there: doctrine/mongodb-odm#861
