### ISSUE TITLE
Aggregation example code 

### ISSUE THREAD

**Issue by Sshuichi** [doctrine/DoctrineMongoDBBundle#240]
It's not really an issue as it is a request for documentation.
I was looking for an example for aggregation in doctrine but I couldn't find any in this website,https://doctrine-mongodb-odm.readthedocs.org/en/latest/
is this website maintained by you ? If so , can you add a section for aggregate and how to use it ? 
Thanks

**Comment by malarzm** [comment]
As a follow up there's an aggregation builder written by @alcaeus in `doctrine/mongodb`, please see https://github.com/doctrine/mongodb/pull/213 for details as there is no documentation right now and most probably there won't be until https://github.com/doctrine/mongodb-odm/pull/1263 is finished
