### ISSUE TITLE
LoadDataFixturesDoctrineODMCommand MongoDBPurger does not recreate indexes 

### ISSUE THREAD

**Issue by munkie** [doctrine/DoctrineMongoDBBundle#242]
*MongoDBPurger* only drops collections, but in my case there is a need to recreate collections, so indexes where created (and some of them are unique), and also i have logic bound to *preCreateCollection* event.
But It is not possible to use custom *MongoDBPurger* implementation in *LoadDataFixturesDoctrineODMCommand*.
I would suggest either fetching purger from container or at least extract method with purger creation logic

**Comment by malarzm** [comment]
This is fixed by https://github.com/doctrine/data-fixtures/pull/188
