### ISSUE TITLE
Allow option to pass actual DocumentManager to DocumentType

### ISSUE THREAD

**Issue by malarzm** [doctrine/DoctrineMongoDBBundle#268]
Hi

Is there any particular reason why we can't pass actual ``DocumentManager`` instance to ``DocumentType``? Right now it accepts ``null`` (gets default dm for class from Registry) or ``string`` (gets named dm from Registry). 

Proposed solution: add one more ``if`` in [this normalizer](https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Form/Type/DocumentType.php#L62)

**Comment by alcaeus** [comment]
Merged manually in https://github.com/doctrine/DoctrineMongoDBBundle/commit/bfc117dae240dd5cf0292e265b87fb49194e8051.
