### ISSUE TITLE
SSL can only be 'true' or 'false'

### ISSUE THREAD

**Issue by cjgordon** [doctrine/DoctrineMongoDBBundle#272]
Hi All,

I am having trouble with the config option 'ssl'.

When I set this to false I get this error:
CRITICAL - Uncaught PHP Exception MongoConnectionException: "SSL can only be 'true' or 'false'" at /home/project/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php line 293 

When looking at the stack I can see:
at MongoClient ->__construct ('mongodb://localhost:27017', array('db' => 'test', 'ssl' => '', 'username' => 'testusr', 'password' => 'today123')) 
in /home/project/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php at line 293  

As you can see for some reason ssl is blanked out in the MongoClient constructor. Interestingly if I manually vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php and add $options['ssl'] = 0 at line 285 it works as expected.

Any ideas?

Thanks in advance.

Cheers
Chris

**Comment by malarzm** [comment]
FWIW Bundle's configuration uses [`booleanNode` for ssl](https://github.com/doctrine/DoctrineMongoDBBundle/blob/581089c6aef7dad44129187b84b17a338401c5e0/DependencyInjection/Configuration.php#L243) so value should be transformed properly. If that's not the case please feel free to reopen the issue.

**Comment by tkuldeep** [comment]
I am facing same problem. When I am passing 
```
  ssl: true
```
it is working fine. but when I am using 
```
  ssl: false
```
in config.yml it is giving error. 
```
Uncaught PHP Exception MongoConnectionException: "SSL can only be 'true' or 'false'" at /home/ubuntu/synpost/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php line 285 {"exception":"[object] (MongoConnectionException(code: 23): SSL can only be 'true' or 'false' at /home/ubuntu/synpost/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php:285)"}
```
I am using symfomy 2.6 and 3.0.2 version of mongo-db-odm-bundle.

Please help me. Thanks in advance.
