### ISSUE TITLE
dialog purge database in Load Fixtures command

### ISSUE THREAD

**Issue by gianarb** [doctrine/DoctrineMongoDBBundle#273]
Hi! ORM fixtures load command support a secure dialog.. This feature not exists for mongodb
![](http://s18.postimg.org/u34r6jxx5/mongo_odm_dialog_fixtures.png)

**Comment by alcaeus** [comment]
Merged manually in https://github.com/doctrine/DoctrineMongoDBBundle/commit/f9201d425446b61b421ab7fa3e4d5499ce33f671.
