### ISSUE TITLE
Superfluous $unset query when using "set" collection strategy 

### ISSUE THREAD

**Issue by seb0zz** [doctrine/DoctrineMongoDBBundle#283]
Hi,

I have a document which has some embedded documents. For that I use the EmbedMany annotation with the collection strategy "set". The strange thing is that every time I update this field of the document Doctrine automatically triggers an $unset query before. 

Does this have a reason or is it a bug?

**Comment by stof** [comment]
This is probably more an issue in the Doctrine ODM than in the bundle.

**Comment by seb0zz** [comment]
https://github.com/doctrine/mongodb-odm/issues/1011

**Comment by seb0zz** [comment]
@malarzm posted an update on the linked issue. @stof maybe you have an idea where the problem comes from if you see his answer.

**Comment by malarzm** [comment]
I've just added small update on the linked issue. I think it would be great to have small test case to see what's really causing the ``$unset`` to be called

**Comment by stof** [comment]
Can you provide a reproducing testcase ?

**Comment by malarzm** [comment]
We have decided to fix the issue in ODM (https://github.com/doctrine/mongodb-odm/issues/1011#issuecomment-103855461) so I'm closing this ticket here
