### ISSUE TITLE
Problem with gridfs when using cache

### ISSUE THREAD

**Issue by librecourage** [doctrine/DoctrineMongoDBBundle#29]
When I attempt to save a document with an attachment, an exception is thrown :

MongoException: zero-length keys are not allowed, did you use $ with double quotes? (uncaught exception) at _/vendor/doctrine-mongodb/lib/Doctrine/MongoDB/Collection.php line 146 

But when i restart my apache server, the document is normally saved without any exception. But the second time, when saving a new document, the exception is thrown again.

Strange...
Seeing my configuraytion file, I comment the parameter  metadata_cache_driver: apc. And then, the problem disappears.

**Comment by alcaeus** [comment]
The patch was added to ODM a while back, closing this.
