### ISSUE TITLE
Document formtype throws TransformationFailedException

### ISSUE THREAD

**Issue by integratedforpublishers** [doctrine/DoctrineMongoDBBundle#290]
When we use the "document" FormType a transformation error is thrown:

Unable to reverse value for property path "block": The choice "82d05e1e26fa38e3bf336f9ba68c5dc5" does not exist or is not unique

Document/field defenition:
```php
    /**
     * @var ContentBlock
     * @ODM\ReferenceOne(targetDocument="Integrated\Bundle\ContentBundle\Document\Block\ContentBlock")
     * @Type\Field(
     *      type="document",
     *      options={
     *          "class"="IntegratedContentBundle:Block\ContentBlock",
     *          "property"="title",
     *          "placeholder"=""
     *      }
     * )
     */
```

Queries executed by Doctrine:
db.block.find({ "_id": "82d05e1e26fa38e3bf336f9ba68c5dc5", "class": { "$in": [ "Integrated\Bundle\ContentBundle\Document\Block\ContentBlock" ] } }).limit(1).limit();
db.block.find({ "_id": [ "82d05e1e26fa38e3bf336f9ba68c5dc5" ], "class": { "$in": [ "Integrated\Bundle\ContentBundle\Document\Block\ContentBlock" ] } });

The second query is wrong, because the _id is passed as array, so it doesn't give results.

Workaround to fix the problem is to add "expanded"=true to the field options. When we do this no query is executed at all to find the the chosen document.

Doctrine versions:
doctrine/annotations                  v1.2.3                                   MIT
doctrine/cache                        v1.4.0                                   MIT
doctrine/collections                  v1.2                                     MIT
doctrine/common                       v2.4.2                                   MIT
doctrine/data-fixtures                v1.0.0                                   MIT
doctrine/dbal                         v2.5.1                                   MIT
doctrine/doctrine-bundle              v1.4.0                                   MIT
doctrine/doctrine-cache-bundle        v1.0.1                                   MIT
doctrine/inflector                    v1.0.1                                   MIT
doctrine/instantiator                 1.0.4                                    MIT
doctrine/lexer                        v1.0.1                                   MIT
doctrine/mongodb                      1.1.8                                    MIT
doctrine/mongodb-odm                  1.0.0-BETA12                             MIT
doctrine/mongodb-odm-bundle           v3.0.0-BETA6                             MIT
doctrine/orm                          v2.4.7                                   MIT

**Comment by zeliard91** [comment]
I have the same issue, this was due to a bug in symfony's latest releases (2.6.5 and 2.3.26)
See https://github.com/symfony/symfony/issues/13961
Go back to the older release until a new one includes the patch.

**Comment by integratedforpublishers** [comment]
@zeliard91 thank you very much. I will close this issue.
