### ISSUE TITLE
schema:update on uninitialized database leads to segmentation fault

### ISSUE THREAD

**Issue by peterrehm** [doctrine/DoctrineMongoDBBundle#294]
Since the latest update there are Segmentation faults occuring if you run an schema:update if the database has not been created previously.

````php
$ app/console doctrine:mongodb:schema:update
Segmentation fault (core dumped)
$ app/console doctrine:mongodb:schema:drop
Dropped indexes for all classes
Dropped collections for all classes
Dropped dbs for all classes
$ app/console doctrine:mongodb:schema:create
Created dbs for all classes
Created collections for all classes
Created indexes for all classes
$ app/console doctrine:mongodb:schema:update
Updated indexes for all classes
$ app/console doctrine:mongodb:schema:drop
Dropped indexes for all classes
Dropped collections for all classes
Dropped dbs for all classes
$ app/console doctrine:mongodb:schema:update
Segmentation fault (core dumped)
````

Is this the intended behaviour?

**Comment by koengsen** [comment]
> Is this the intended behaviour?

Yes. Yes it is!

**Comment by alcaeus** [comment]
Going out on a limb here, could this be related to https://github.com/doctrine/mongodb-odm/pull/1045#issuecomment-95617176?
Can you post the MongoDB server/driver versions involved?

**Comment by jmikola** [comment]
@alcaeus: This is very likely, since `schema:update` attempts to create indexes and likely calls `getIndexInfo()`. I'll attempt to get 1.6.7 (with the fix) released shortly.

**Comment by peterrehm** [comment]
````
Installed Libraries:
doctrine/mongodb                      1.1.8              Doctrine MongoDB A...
doctrine/mongodb-odm                  dev-master 0de70ab Doctrine MongoDB O...
doctrine/mongodb-odm-bundle           dev-master 428c21f Symfony2 Doctrine ...

$ mongod --version
db version v3.0.2

PHP Driver 1.6.6
````

Looks like @jmikola identified the cause. Once 1.6.7 is released I can give it a try.

**Comment by jmikola** [comment]
Released: https://pecl.php.net/package/mongo/1.6.7

**Comment by peterrehm** [comment]
Thanks, it fixed the issue as expected.

**Comment by jmikola** [comment]
@peterrehm: Good to hear! :+1:
