### ISSUE TITLE
Does it support mongoDB 3.0

### ISSUE THREAD

**Issue by elyotechgit** [doctrine/DoctrineMongoDBBundle#296]
Hello, 

I didn't succeed to find information through google or on the doctrine website.
Does the DoctrineMongoDB ODM is already supporting the last version of mongoDB 3.0 ?
Does DoctrineMongoDB Bundle is supporting the latest DoctrineMongoDB ?

Thanks for your helps/answers.

**Comment by malarzm** [comment]
According to http://docs.mongodb.org/ecosystem/drivers/php/ version 1.6 of driver does support mongoDB 3.0 so you should be fine as https://github.com/doctrine/mongodb builds on the driver. If something goes wrong please report :)

**Comment by jmikola** [comment]
Indeed. There were some early compatibility issues with 2.8 (since renamed to 3.0), but those should have been fixed in [Doctrine MongoDB|https://github.com/doctrine/mongodb].

**Comment by elyotechgit** [comment]
Thanks
