### ISSUE TITLE
setDefaultRepositoryClassName is not defined

### ISSUE THREAD

**Issue by zeliard91** [doctrine/DoctrineMongoDBBundle#298]
The PR #297 added a call to `Doctrine\ODM\MongoDB\Configuration::setDefaultRepositoryClassName()` but this method is present only in `"doctrine/mongo-odm":"dev-master"` for the moment as it has been merged by https://github.com/doctrine/mongodb-odm/pull/892), so after the tag `1.0.0-BETA12`.

@malarzm I don't know if the PR should be 'reverted', maybe it's preferable to wait for a new `doctrine/mongodb-odm` release than change the version requirement to dev-master.

**Comment by malarzm** [comment]
I'm thinking about checking if ``default_repository_class`` is different than default one and if so then add a call to `Doctrine\ODM\MongoDB\Configuration::setDefaultRepositoryClassName()` but also we will discuss the issue internally and try to provide the best fix.

**Comment by malarzm** [comment]
@zeliard91 we have tagged [v3.0.0](https://github.com/doctrine/DoctrineMongoDBBundle/releases/tag/v3.0.0) :)

**Comment by zeliard91** [comment]
@malarzm great job, thank you !
