### ISSUE TITLE
getQuery(array('multiple'=>true)) is not working

### ISSUE THREAD

**Issue by fernanDOTdo** [doctrine/DoctrineMongoDBBundle#30]
Hi!
I dont know if its a problem with doctrine-mongodb-odm or DoctrineMongoDBBundle.
I am trying to do something like this:

$parameters->createQueryBuilder()
                                ->update()
                                ->field('id')->equals($tk)
                                ->field('children.fieldtype')->equals('checkbox')
                                ->field('children.$.value')->set(0)
                                ->getQuery(array('multiple'=>true))
                                ->execute();

The result according to the log is:

db.parameters.update({ "_id": "system-site", "children.fieldtype": "checkbox" }, { "$set": { "children.$.value": 0 } });

I guess its just "multiple": true that is missing.

Thank you and sorry about my bad english :)

**Comment by malarzm** [comment]
This is correct way now for updating multiple documents: http://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/query-builder-api.html#updating-multiple-documents
