### ISSUE TITLE
Not all queries are shown in debug

### ISSUE THREAD

**Issue by johnpancoast** [doctrine/DoctrineMongoDBBundle#303]
Certain queries do not show up in the symfony debugger. These are queries I know run and I know get results but they are not in the debugger at all.

I'm not sure what information to provide. The query that isn't in the debugger was run by using something similar to this. I can verify that $doc in fact ran and has results.

```
$doc = $documentManager
  ->getRepository('FooRepo')
  ->findOneByFoo('foo');
```

**Comment by alcaeus** [comment]
The query you showed is properly logged and displayed in the profiler:
> use db;
> db.fooRepo.find({ "foo": "foo" }).limit(1);

If you have a specific query that doesn't appear, feel free to reopen this issue with the query in question.
