### ISSUE TITLE
DoctrineODMCommand::findBasePathForBundle fails with some PSR-4 configurations

### ISSUE THREAD

**Issue by castarco** [doctrine/DoctrineMongoDBBundle#307]
There are many PSR-4 namespace configurations that don't work properly with some Doctrine ODM commands because poor error condition handling.

I've done a pull request to fix it #306 . It's not a final solution, so it's completely open to discussion. You can find more info in the pull request.

**Comment by malarzm** [comment]
I'm assuming this was fixed with #308 so I'm closing this issue. Please feel free to re-open if that's not true :)
