### ISSUE TITLE
YAML / XML Mapping Driver

### ISSUE THREAD

**Issue by dominikzogg** [doctrine/DoctrineMongoDBBundle#311]
Are those still needed?

https://github.com/doctrine/DoctrineMongoDBBundle/tree/master/Mapping/Driver

see:
https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Driver/SimplifiedXmlDriver.php
https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Driver/SimplifiedYamlDriver.php

**Comment by stof** [comment]
no, they are not really needed. These classes should be deprecated in favor of the ODM classes themselves.
