### ISSUE TITLE
Documentation: Document the additional form field types

### ISSUE THREAD

**Issue by johnpancoast** [doctrine/DoctrineMongoDBBundle#312]
This bundle includes an additional form type `document` to be used in place of `entity` that isn't documented anywhere from what I can tell. The only way I found it was from reviewing code, stackoverflow, and what seems like common knowledge for people at this point but that doesn't help the new people.

There may be other types I'm unaware of and I believe it includes additional data transformers too.

Where can I help?

_[edited for clarity, think there's only the one additional type among other things]_

**Comment by malarzm** [comment]
From what I see there was supposed to be a chapter about it on http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#learn-more-from-the-cookbook but for some reason it's not there :baby: Maybe we should create a chapter about integrations in ODM's documentation? @jmikola what do you think?

**Comment by shideon** [comment]
Yea I noticed that and you can actually go to http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/form in browser. But that page doesn't have enough info on the additional form types.

**Comment by malarzm** [comment]
@shideon feel free to make a PR against this repo, docs are located in https://github.com/doctrine/DoctrineMongoDBBundle/tree/master/Resources/doc and surely can use some attention :)

**Comment by shideon** [comment]
I'll have a look when I can.

**Comment by malarzm** [comment]
I still think we should document this somehow

**Comment by johnpancoast** [comment]
Apologies everyone. I know it's the same old tired excuse. As always, I try to commit to these things, but I've been all over the place with several other projects, including music and other things. I know that others are in the same boat and they're still able to help out, so it's a poor excuse, but that's just the reality for me at the moment.

Agree with @malarzm, this should absolutely be documented from what I remember. I'll check out the docs later this week unless someone else beats me to it. Committed!

**Comment by malarzm** [comment]
@johnpancoast thanks a lot!

**Comment by alcaeus** [comment]
@johnpancoast don't worry about it, thanks for still giving it a shot. Let us know if you can't make it as we'll be doing a docs pass before the next round of releases to finally get some of these undocumented features documented better.

**Comment by johnpancoast** [comment]
@malarzm and @alcaeus, thanks for understanding. This week was more of the same along with a minor 🚲 accident over the weekend! Needless to say, I did not get to this.

> Let us know if you can't make it as we'll be doing a docs pass before the next round of releases

@alcaeus, when were these releases planned?

**Comment by johnpancoast** [comment]
Hmm, so TBH, I don't think there needs to be much added to the docs. Perhaps something as simple as:

> Note that this bundle adds a new form type called `document` which is functionally equivalent to the [entity](https://symfony.com/doc/current/reference/forms/types/entity.html) form type, except that it loads options from a Doctrine ODM Document instead of a Doctrine entity.

I'm just not sure where I should add that. Thoughts?

**Comment by alcaeus** [comment]
You can add a `form` section to the main documentation (https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Resources/doc/index.rst). It's already quite busy so we'll have to rewrite it sooner or later, but for now I think it's best to mention it there.

**Comment by malarzm** [comment]
FWIW I started splitting the docs yesterday as the index is way too huge.
