### ISSUE TITLE
MongoDB 3.0 support?

### ISSUE THREAD

**Issue by omnidan** [doctrine/DoctrineMongoDBBundle#315]
[mongolab](https://mongolab.com/) recently upgraded to MongoDB 3.0, which broke everything for me. I updated all libraries and the PHP driver, I even manually added the new `SCRAM-SHA-1` auth mechanism as an option to doctrine, but I'm still getting the following error:

```
Failed to connect to: XXX.mongolab.com:XXX: SASL Authentication failed on database 'YYY': Authentication failed
```

**Comment by malarzm** [comment]
@omnidan I admit I haven't looked myself into upgrading to 3.0, is this missing option in bundle or what is causing the error?

**Comment by omnidan** [comment]
@malarzm The solution was just upgrading the PHP driver and leaving the library on the current version, it seems to work fine now. In the `authMechanism` option the new (default) option in 3.0: `SCRAM-SHA-1` is missing.

I created a pull request to add this option: https://github.com/doctrine/DoctrineMongoDBBundle/pull/316

**Comment by malarzm** [comment]
Cool, PR's merged, thank you!

**Comment by omnidan** [comment]
You're welcome :grin:
