### ISSUE TITLE
Question/suggestion

### ISSUE THREAD

**Issue by acrozes** [doctrine/DoctrineMongoDBBundle#317]
When we make updates of document's mapping there are some fields removed. But there are not in mongodb.
Is exist a way to remove automaticaly this old fields, maybe a command could do the job ? 
Thanks.

**Comment by alcaeus** [comment]
You can use a tool like [Mongeez](https://github.com/secondmarket/mongeez) to manage something like a schema in your MongoDB database; the ODM itself does not come with a command like this.

**Comment by malarzm** [comment]
FWIW you could try employing https://github.com/doctrine/migrations or roll your own migration tool (I did, it's not that complicated :) )

**Comment by acrozes** [comment]
I don't know if the migration tool can be adapt to ODM, particularly on the way to created the diff schema between two version ...

Maybe a simple @removeField annotation with a command doctrine:mongodb:schema:clean ?

**Comment by malarzm** [comment]
> Maybe a simple @removeField annotation with a command doctrine:mongodb:schema:clean ? 

For the record I'm opposed to this, however if somebody wants to elaborate please do so by opening new issue in ODM itself :)
