### ISSUE TITLE
Show query time in profiler

### ISSUE THREAD

**Issue by marijnotte** [doctrine/DoctrineMongoDBBundle#319]
In dev mode, it would be great to see the query time for each query (like the Doctrine ORM profiler does: http://take.ms/37ILV). This makes it a lot easier to identify queries that are subject for performance improvement.

**Comment by ChubV** [comment]
Yeah, to make it happen  you have to do something like https://github.com/doctrine/mongodb/pull/153

**Comment by jmikola** [comment]
Note: the [command monitoring](http://php.net/manual/en/mongodb.tutorial.apm.php) functionality in the newer `mongodb` extension may be helpful, as the information could be captured without requiring any modifications to ODM.

**Comment by alcaeus** [comment]
Scheduling for 4.0.0 which will be the first major version to require ODM 2.0, which will require the new driver. We can then finally start implementing this feature. In the meantime, please show your support using emotions instead of `+1` comments 😉

**Comment by IonBazan** [comment]
Implemented in #652 - will be released as 4.4.0 soon.
