### ISSUE TITLE
SingleCollectionInherance and generate documents

### ISSUE THREAD

**Issue by gimler** [doctrine/DoctrineMongoDBBundle#33]
When you use Single Collection Inheritance the command php app/console doctrine:mongodb:generate:documents throw a exception

[Doctrine\ODM\MongoDB\MongoDBException]
No identifier/primary key specified for Document 'Savedcite\CiteBundle\Document\CiteBook'. Every Document must have an identifier/primary key.

So the problem is that it not check the parent class ;(

**Comment by alcaeus** [comment]
Closing since this is an ODM issue. If it persists, please open a ticket at https://github.com/doctrine/mongodb-odm/issues. Thanks!
