### ISSUE TITLE
Recommended Field Type Mapping annotations

### ISSUE THREAD

**Issue by webdevilopers** [doctrine/DoctrineMongoDBBundle#334]
Seems like the annotation example is currently missing:
https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Resources/doc/index.rst#add-mapping-information

The docs state:
`If you use annotations, you'll need to prepend all annotations with MongoDB\ (e.g. MongoDB\String), which is not shown in Doctrine's documentation.`

The offical doctrine docs uses the `Field` annotation to define the `type`:
```php
    /** @Field(type="string") */
    private $username;
```

http://doctrine-orm.readthedocs.org/projects/doctrine-mongodb-odm/en/latest/reference/basic-mapping.html#fields

Is the type mapping equivalent to:
```php
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

    /**
     * @MongoDB\String
     * @MongoDB\Field(name="username")
     */
    private $username;
```
or should it be:
```php
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;

    /**
     * @MongoDB\Field(type="string", name="username")
     */
    private $username;
```
?

**Comment by malarzm** [comment]
Go with `@MongoDB\Field(type="string", name="username")` as we're going to deprecate `@MongoDB\String` because of PHP 7 :)

**Comment by malarzm** [comment]
Ah also @webdevilopers you linked to ORM documentation which doesn't have separate types as annotations :)

**Comment by webdevilopers** [comment]
Thanks @malarzm !

You mean http://doctrine-orm.readthedocs.org/projects/doctrine-mongodb-odm/en/latest/reference/basic-mapping.html#fields ? The ORM comes just from the doctrine URL, or?
Here is a list of the types in my first link:
https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Resources/doc/index.rst#doctrine-field-types-reference

**Comment by malarzm** [comment]
Oh sorry, I saw orm in the subdomain and haven't clicked it - I apologize for my mistake :)
