### ISSUE TITLE
Documentation is specifying incorrect yaml file suffix

### ISSUE THREAD

**Issue by johnpancoast** [doctrine/DoctrineMongoDBBundle#357]
The documentation both [here](http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#add-mapping-information) and [here](http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html#mapping-configuration) says to suffix yaml mapping files with `.mongodb.yml` but this errors with `Bundle AcmeStoreBundle does not contain any mapped documents.Did you maybe forget to define a mapping configuration?`

Judging by [this code](https://github.com/doctrine/mongodb-odm/blob/master/lib/Doctrine/ODM/MongoDB/Mapping/Driver/SimplifiedYamlDriver.php#L31) it looks like the expected suffix is actually `.mongodb-odm.yml` and when I change to that the file is mapped properly.

Are those docs in a repo somewhere? Can't remember.

**Comment by malarzm** [comment]
Yes, they're here: https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Resources/doc/index.rst - PR fixing that is welcome :)

**Comment by johnpancoast** [comment]
@malarzm I poked around a bit. It looks like it was commit 280a01a522acb51c7638e7ea625228bd8374d9cc that changed things. Where/how do the "raw" mapping files get loaded though? The ones referenced [here](https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Resources/doc/config.rst#mapping-configuration).

> If you are using xml, yml or php mapping put all your configuration files into the Resources/config/doctrine/ directory suffixed with mongodb.xml, mongodb.yml or mongodb.php respectively.

**Comment by malarzm** [comment]
Hmmm @alcaeus seems like we've indeed overlooked file suffix difference between drivers here and in ODM (i.e. [.mongodb-odm.yml](https://github.com/doctrine/mongodb-odm/blob/0573f48b25e16633ad4fd2c1490a0bb65d3c7354/lib/Doctrine/ODM/MongoDB/Mapping/Driver/SimplifiedYamlDriver.php#L31) vs [.mongodb.yml](https://github.com/doctrine/DoctrineMongoDBBundle/blob/f4d043d533a530841ebbb6efd5889cc20d5af2ef/Mapping/Driver/YamlDriver.php#L31)). Are we sticking to the decision and still deprecating the ones here? Theoretically we could load both in ODM's `SimplifiedYAMLDriver`?

**Comment by alcaeus** [comment]
Yes, I totally overlooked this - I apologize. Indeed, I would continue with our plan to deprecate the drivers contained in the bundle as they don't add any functionality. Nonetheless, we should make sure existing files get still loaded.

**Comment by malarzm** [comment]
@johnpancoast would you mind testing #358?

**Comment by johnpancoast** [comment]
@malarzm Sure when I'm out of office. Will update in a few hrs.

**Comment by malarzm** [comment]
Thanks in advance!

**Comment by johnpancoast** [comment]
Hmm seems to still be doing the same thing.

**Comment by malarzm** [comment]
Crap... Ok, I'll try to dig deeper then

**Comment by malarzm** [comment]
"Old" extensions will still work thanks to #361
