### ISSUE TITLE
Can I use this bundle with mongodb.so extension?

### ISSUE THREAD

**Issue by vkost** [doctrine/DoctrineMongoDBBundle#364]
Hi guys,
I love your bundle and I use it on several Symfony2 projects. Today I tried to update my local system to use mongodb.so instead of mongo.so I used so far. However, once I replaced the extension with the new one system started reporting errors. I was wondering, is this bundle able to work with new mongodb.so or I must use the old one?

Thanks,
Vic

**Comment by Enleur** [comment]
It does not support it yet. Try https://packagist.org/packages/alcaeus/mongo-php-adapter

**Comment by vkost** [comment]
Thank you very much - I'll stick with the mongo.so for the moment then...
I presume there is a plan to move this extension to mongodb.so?

Cheers

**Comment by Enleur** [comment]
Doctrine mongodb team are hardly working on support of the new driver right now. You can follow progress here https://github.com/doctrine/mongodb/issues/239. Hope it's going to be released soon

**Comment by vkost** [comment]
Thanks again
Cheers
