### ISSUE TITLE
Symfony mongodb objectID error 

### ISSUE THREAD

**Issue by Diarselimi** [doctrine/DoctrineMongoDBBundle#376]
Im trying to insert data into mongodb from symfony, and i got the error like 
> Attempted to load class "ObjectID" from namespace "MongoDB\BSON".
Did you forget a "use" statement for another namespace?
i checked the file MongoId.php and the else part new ObjectID(); requires a parameter but there is none
> in vendor/alcaeus/mongo-php-adapter/lib/Mongo/MongoId.php at line 215 

`
            } elseif ($id instanceof self || $id instanceof ObjectID) {
                $this->objectID = new ObjectID((string) $id);
            } else {
                $this->objectID = new ObjectId();
            }
        } catch (\Exception $e) {
            throw new MongoException('Invalid object ID', 19);
`

**Comment by alcaeus** [comment]
This looks like it could be an issue in mongo-php-adapter. I've created an issue there and will take a look at it later today. Thanks for the report!

**Comment by alcaeus** [comment]
I've fixed this in mongo-php-adapter - could you give `dev-1.0.x` a quick test run?

**Comment by capozzid** [comment]
I still have the same issue with 1.0.9

**Comment by yivi** [comment]
I know this is supposed to be closed, but I'm getting exactly the same error on a fresh install...

**Comment by bfday** [comment]
PHP 7.0.15-0ubuntu0.16.04.4
"symfony/symfony": "3.2.*"
To solve the proble i've used this [https://github.com/doctrine/DoctrineMongoDBBundle/issues/376](url)
And this [http://stackoverflow.com/questions/36964171/php-7-with-doctrine-mongodb-odm](url)
All the process 

[PHP Modules]
```
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mongodb
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib
```

composer.json
```
{
    "name": "bfday/url-shortener",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.2.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "twig/twig": "^1.0||^2.0",
        "twbs/bootstrap": "^3.3",
        "mongodb/mongodb": "^1.1",
        "alcaeus/mongo-php-adapter": "^1.1",
        "doctrine/mongodb-odm": "^1.0",
        "doctrine/mongodb-odm-bundle": "^3.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": null
    }
}
```

Nothing helps.

**Comment by thmohd** [comment]
I am still having same issue:

> Attempted to load class "ObjectID" from namespace "MongoDB\BSON".
Did you forget a "use" statement for another namespace?

**Comment by alcaeus** [comment]
Please create a ticket at https://github.com/alcaeus/mongo-php-adapter/issues along with the following information:
* Version of mongo-php-adapter used
* Version of ext-mongodb used
* Your operating system

I'm closing this ticket since this is not an issue with the bundle or with MongoDB ODM, so future issues will be directed to the adapter directly.
