### ISSUE TITLE
DocumentType : Cannot reuse resolved option to recreate the field from a FormEvent

### ISSUE THREAD

**Issue by Alsatian67** [doctrine/DoctrineMongoDBBundle#377]
In a Symfony app, I have a listener that disables each non-empty field :

``` php
class ChangesSubscriber implements EventSubscriberInterface
{
    public function postSetData(FormEvent $event)
    {
        $form = $event->getForm();

        foreach($form->all() as $child)
        {
            $childName = $child->getName();
            $childType = get_class($child->getConfig()->getType()->getInnerType());

            $childOptions = $child->getConfig()->getOptions(); 

            if(!$child->isEmpty()){
                $form->add($childName,$childType,array_merge($childOptions,array('disabled'=>true)));
            }
        }
    }
}
```

It works for every Symfony built-in FormTypes, but with the documenttype it throws this error :

>  You cannot set both an "em" and "document_manager" option.
> 
> Stack Trace
> 
> ```
> in vendor/doctrine/mongodb-odm-bundle/Form/Type/DocumentType.php at line 57  -
>             $registry = $this->registry;
>             $normalizer = function (Options $options, $manager) use ($registry) {
>                 if (isset($options['document_manager']) && $manager) {
>                     throw new \InvalidArgumentException('You cannot set both an "em" and "document_manager" option.');
>                 }
>                 $manager = $options['document_manager'] ?: $manager;
> ```

And I had never used em or document_manager options ...

[Symfony binded issue](https://github.com/symfony/symfony/issues/19337)

**Comment by Alsatian67** [comment]
* I neither set em or document_manager as option.

**Comment by Alsatian67** [comment]
I bypassed this bug with :

```php
$options = $child->getConfig()->getOptions();
if(array_key_exists('em',$options)){unset($options['em']);}
```

**Comment by malarzm** [comment]
I'm far from being an expert when it comes to forms, but to me it looks like the problem boils down to type's config being resolved for the second type (so an already resolved configuration is passed again in your `add`). Most probably the same will happen with any other type that has some safeguards against configuration values it wants to set by itself.

**Comment by Alsatian67** [comment]
I also thought so in my [Symfony issue](https://github.com/symfony/symfony/issues/19337), that's why I did a feature request to be able to retrieve only the options 'passed during construction', core members said no, it should be bad usage in my app. Then I tested it with all the fields I use.

And I have only problems with the DocumentType.

**Comment by Alsatian67** [comment]
If I just remove that

```php
if (isset($options['document_manager']) && $manager) {
    throw new \InvalidArgumentException('You cannot set both an "em" and "document_manager" option.');
}
```

Everything wokrs.

I think we could refactore this verification to ignore 'document_manager' when 'em' is set ?

**Comment by malarzm** [comment]
> I think we could refactore this verification to ignore 'document_manager' when 'em' is set ?

That could quietly hide an issue for somebody so I'm not much for this solution. Also I'd rather see this fixed in Symfony as stated previously, this can happen to any form type having such normalizers/checks.

Offhand, I was also struggling with form modifications depending on underlying model data and/or some context and that's how we came up with https://github.com/codete/FormGeneratorBundle. General idea is that all fields' configuration is held in arrays until every hook had chance to modify it knowing context and only at the end concrete form types are being created. Works like a charm for my project :)

**Comment by Alsatian67** [comment]
OK, thank you for your advices :)

But I have till something strange :

Hooking in the verification, I have :

```php
        $normalizer = function (Options $options, $manager) use ($registry) {
            if (isset($options['document_manager']) && $manager) {
				exit(dump(array(isset($options['document_manager']),$options['document_manager'])));
                throw new \InvalidArgumentException('You cannot set both an "em" and "document_manager" option.');
            }

            $manager = $options['document_manager'] ?: $manager;

            if (null === $manager) {
                return $registry->getManagerForClass($options['class']);
            }

            if ($manager instanceof ObjectManager) {
                return $manager;
            }

            return $registry->getManager($manager);
        };
```

And the dump result :

```
DocumentType.php on line 57:
array:2 [▼
  0 => true
  1 => null
]
```

How can isset($options['document_manager']) return true when $options['document_manager'] = null ??

(Config : PHP 7.0.9 / Symfony 3.1.3)

**Comment by malarzm** [comment]
> How can isset($options['document_manager']) return true when $options['document_manager'] = null ??

[`OptionsResolver`](https://github.com/symfony/options-resolver/blob/45940bcad6388b3b6058107eca67ced738d205bb/OptionsResolver.php) is implementing `\ArrayAccess` thus `isset` check calls [`offsetExists`](https://github.com/symfony/options-resolver/blob/45940bcad6388b3b6058107eca67ced738d205bb/OptionsResolver.php#L909) method which only checks if the key in question exists or not ([relevant part of PHP docs](http://php.net/manual/en/arrayaccess.offsetexists.php))

**Comment by Alsatian67** [comment]
OK, and by a normal array :
```php
$a = array('foo'=>null);
isset($a['foo']); // return false
```

So is it really intended in the DocumentType normalizer to trhow the exception, when $options['document_manager'] = null ?

**Comment by Alsatian67** [comment]
I think this :

```php
if (isset($options['document_manager']) && $manager) {
	throw new \InvalidArgumentException('You cannot set both an "em" and "document_manager" option.');
}
```

Should be son since a null 'document_manger' doesn't hurt :

```php
if (isset($options['document_manager']) && $options['document_manager'] && $manager) {
	throw new \InvalidArgumentException('You cannot set both an "em" and "document_manager" option.');
}
```

**Comment by malarzm** [comment]
This would make `null` effectively bypass safeguard and given `null` is correct value, as it is supposed to find document manager for given `class`, it doesn't seem to be wanted effect.

On a second thought, original `DoctrineType` doesn't seem to forbid changing `em` (and the safeguard seems to be in place to prevent using `em` option) so contrary to your proposition

> I think we could refactore this verification to ignore 'document_manager' when 'em' is set ?

I think we could ignore `em` being set and always normalize what is given in `document_manager` so basically throw away the safeguard altogether. Thoughts?

**Comment by Alsatian67** [comment]
Good idea.

**Comment by Alsatian67** [comment]
Sorry for the late answer, but no, it won't solve my initial problem. When I reuse the resolved options to rebuild the same form, I will receive a 'em' option, and nothing as 'document_manager' ...

Just let the code as it is, and if someone else has the same problem, he can use my workout : 
https://github.com/Alsatian67/FormBundle/blob/master/Form/Extensions/ExtensibleSubscriber.php#L74
