### ISSUE TITLE
How to connect to MongoDb with SSL certificate?

### ISSUE THREAD

**Issue by websirnik** [doctrine/DoctrineMongoDBBundle#380]
I have an SSL certificate that I need to use when connecting to MongoDB.

How can I replicate the example #2 from http://php.net/manual/en/mongo.connecting.ssl.php with the DoctrineMongoDBBundle?

**Comment by malarzm** [comment]
This may be not possible with current bundle state as connection's definition is created [here](https://github.com/doctrine/DoctrineMongoDBBundle/blob/6dde855375471bc3e1bf2fad4e3d781efff68d67/DependencyInjection/DoctrineMongoDBExtension.php#L291-L296) and later during initialization the third argument [is not passed](https://github.com/doctrine/mongodb/blob/ac25f8705451b316c6bb5a44bd537fd528dfdd5b/lib/Doctrine/MongoDB/Connection.php#L282) to the driver.

**Comment by malarzm** [comment]
Just to cross reference @alcaeus just opened https://github.com/doctrine/mongodb/pull/276 which provides missing feature in underlying `doctrine/mongodb` so after we release stable version we can add configuration option to the bundle :)

**Comment by manuelbcd** [comment]
+1  It's important to have the ability to connect using SSL certificate file.
