### ISSUE TITLE
Second setCollection not working

### ISSUE THREAD

**Issue by hiniesta** [doctrine/DoctrineMongoDBBundle#395]
I have Document set in collections by year. When I tried to set the collection two times, the second one doesn't work. Here is my script:
`
/* fist select */
$dm = $this->get('doctrine_mongodb')->getManager();
  $dm->getClassMetadata('\MyBundle\Document\Myobject')->setCollection('Myobject_2016');

$resumen = $dm
            ->createQueryBuilder('MyBundle:Myobject')
             ->select()
            ->getQuery()
            ->execute()
            ->toArray();

/* Data from collectio Myobject_2016 -> OK*/

/* second select */
  $dm->getClassMetadata('\MyBundle\Document\Myobject')->setCollection('Myobject_2017');
$resumen2 = $dm
            ->createQueryBuilder('MyBundle:Myobject')
             ->select()
            ->getQuery()
            ->execute()
            ->toArray();
/* Error, $resumen2 query is executed in Myobjecto2016 collection*/
`

Here is the log of the query
`
db.Myobject_2016.find();
db.Myobject_2016.find();`

Any help how to change the second time the document collection?

**Comment by malarzm** [comment]
This is not something ODM is supporting out of the box, you'll need to dive into code to find all places that would need adjusting for such change to take effect (FWIW similar idea was submitted before in https://github.com/doctrine/mongodb-odm/issues/1243 and resolution was that such feature would complicate API too much).

Also next time for support requests please post a question on StackOverflow under `doctrine-odm` tag.
