### ISSUE TITLE
values for multiple, expanded DocumentType are not loaded

### ISSUE THREAD

**Issue by omissis** [doctrine/DoctrineMongoDBBundle#40]
I am trying to print a multiple, expanded form widget(ie: checkboxes) loading its options from mongo. Using the following annotation and letting the form guess everything(or specifing 'document', array('multiple' => true, 'expanded' => true, 'class'=>...)) it works fine when it comes to rendering and submitting:

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     *
     * @MongoDB\EmbedMany(targetDocument="Pizzas")
     */
    protected $pizzas;

Where I am experiencing troubles is on showing results on edit pages. 
Even if the Document is loaded properly, the checkboxes don't get "checked". 
I found a potential source of the problem in Symfony\Bundle\DoctrineMongoDBBundle\Form\DataTransformer\DocumentsToArrayTransformer.php, line 55, 
where $array[] = $this->choiceList->getIdentifierValue($document); gets called. 
Following the flow, I got to Doctrine\ODM\MongoDB\UnitOfWork, method getDocumentIdentifier(): that function checks for the spl_object_hash($document) key into $this->documentIdentifiers and eventually return the corresponding value. The point is that spl_object_hash() won't return the Document (Mongo)id, but one of its own that will never match the ones loaded as choices for the checkboxes, determining the lack of selected options in the editing page.
Changing $array[] = $this->choiceList->getIdentifierValue($document); to $array[] = $document->getId(); in DocumentsToArrayTransformer solves this problem, but I am not sure it's the "right" solution to this problem.

**Comment by alcaeus** [comment]
Took the opportunity to create a test case reproducing it, the issue was fixed sometime between your ticket and now: https://github.com/doctrine/DoctrineMongoDBBundle/commit/66b30191da7fb48431eb51e4bbec07d142ebd0ce
