### ISSUE TITLE
Is there a package that doesn't require the whole framework?

### ISSUE THREAD

**Issue by olvlvl** [doctrine/DoctrineMongoDBBundle#414]
Hi,

I'm using `symfony/form` with MongoBD but without Symfony and I'd like to build a form that handles relations and embedded documents. Is there a version of this package that doesn't require the whole framework? I mean, I don't care about any of these:

```
  - Installing symfony/stopwatch (v3.2.8): Loading from cache
  - Installing symfony/finder (v3.3.0-RC1): Loading from cache
  - Installing symfony/class-loader (v3.2.8): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing symfony/polyfill-util (v1.3.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.3.0): Loading from cache
  - Installing symfony/security-core (v3.2.8): Loading from cache
  - Installing symfony/security-csrf (v3.2.8): Loading from cache
  - Installing symfony/routing (v3.2.8): Loading from cache
  - Installing symfony/cache (v3.2.8): Downloading (100%)
  - Installing symfony/framework-bundle (v3.2.8): Downloading (100%)
```

I think I'm only interested in the `DocumentType` class.

**Comment by alcaeus** [comment]
As this is a bundle, it requires all of the above through one dependency or another. If you're only interested in the `DocumentType` class, you'll have to extract it and port it over. Beware that the `DocumentType` extends the `DoctrineType` from the doctrine bridge, so you'll have to resolve those dependencies as well.

**Comment by olvlvl** [comment]
Thanks @alcaeus, I might just do that.
