### ISSUE TITLE
Documentation : installation for Symfony 3.3

### ISSUE THREAD

**Issue by CedCannes** [doctrine/DoctrineMongoDBBundle#419]
The symfony installer installed on my system the framework in version 3.3.
I wanted to install DoctrineMongoDBBundle to try it but I have a problem with the documentation.
This part : 
http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#register-the-annotations-and-the-bundle

"Next, register the annotations library by adding the following to the autoloader"

In version 3.3 there is no longer this file : app/autoload.php so where I'm supposed to activate the annotations ?

**Comment by malarzm** [comment]
That is quite valid question, need to take a look what actions should be taken now.

**Comment by Lctrs** [comment]
This step is not needed anymore as annotations are autoloaded with Symfony > 3.3. See https://github.com/symfony/recipes-contrib/pull/10#issuecomment-298850520.

**Comment by malarzm** [comment]
@Lctrs thanks for chiming in :) Out of curiosity, where does Symfony actually register the loader? Tried looking for it but brief grep/google yielded no results

**Comment by malarzm** [comment]
Ah never mind, just found related pull request to Symfony

**Comment by Lctrs** [comment]
In the container.

**Comment by malarzm** [comment]
Man, that hack in container is ugly
