### ISSUE TITLE
Why register annotations is required during the installation process

### ISSUE THREAD

**Issue by murilolobato** [doctrine/DoctrineMongoDBBundle#424]
Reading the installation instructions on [symfony.com](https://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#register-the-annotations-and-the-bundle) and in the own [repo docs](https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Resources/doc/index.rst#register-the-annotations-and-the-bundle) (which is referenced by the symfony webpage) it says to add the following code to ```app/autoload.php```:

    use Doctrine\ODM\MongoDB\Mapping\Driver\AnnotationDriver;
    AnnotationDriver::registerAnnotationClasses();

I've just discovered that my application is running without this code about two years. Is this call still necessary? What this does?

**Comment by malarzm** [comment]
This is pre-composer way of including ODM annotations, you can do perfectly fine without it, especially using Symfony. The `AnnotationDriver::registerAnnotationClasses();` call was deprecated and will be removed in ODM 2.0.

**Comment by malarzm** [comment]
Ah, feel free to re-open if you have any suggestions :)
