### ISSUE TITLE
Attempted to load class “ObjectID” from namespace “MongoDB\BSON”

### ISSUE THREAD

**Issue by elshobokshy** [doctrine/DoctrineMongoDBBundle#439]
I'm trying to use DoctrineMongoDBBundle but it gives me this error :

> Attempted to load class "ObjectID" from namespace "MongoDB\BSON". 
> Did you forget a "use" statement for another namespace?

I've searched all over for a reason, but I could not find why I get this error.

My mongodb is installed alright, a mongodb status tells me it's active. I think I correctly set up the classes... etc. Where can the error be coming from?

**Comment by malarzm** [comment]
Please check the driver you have installed and follow http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/introduction.html#using-php-7 if you want to use ODM with PHP 7.

**Comment by elshobokshy** [comment]
@malarzm I already did everything said in that link. Nothing seems to work. I asked a [question on stackoverflow ](https://stackoverflow.com/questions/47354109/attempted-to-load-class-objectid-from-namespace-mongodb-bson) but no one seems to know why do I have such an error. You can check in that link the things I tried... I'm desperate for help :(

**Comment by bitgandtter** [comment]
to use mongodb with php 7.x > you need to include alcaeus/mongo-php-adapter since doctrine does not provide an integration with the new library implementation

**Comment by alcaeus** [comment]
@elshobokshy in your stackoverflow question, your code failed when calling `app_dev.php`, meaning it was running in FPM or as an apache module, but you checked for the `mongodb` extension in the PHP CLI. Could you check for `extension_loaded('mongodb')` in your `app_dev.php` and report back what it tells you?

**Comment by malarzm** [comment]
Closing due to lack of feedback from OP.
