### ISSUE TITLE
Autowiring for repository classes

### ISSUE THREAD

**Issue by xorik** [doctrine/DoctrineMongoDBBundle#443]
The ORM bundle have a helper class to make repositoires autowired. The class is `ServiceEntityRepository`. Example is [here](https://github.com/symfony/demo/blob/master/src/Repository/PostRepository.php).

It would be great, if ODM bundle have the same for the `DocumentRepository` class.

I think something like this should work:
```php
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\DocumentRepository;

class ServiceDocumentRepository extends DocumentRepository
{
    public function __construct(DocumentManager $dm, string $documentClass)
    {
        parent::__construct($dm, $dm->getUnitOfWork(), $dm->getClassMetadata($documentClass));
    }
}
```

**Comment by alcaeus** [comment]
@michaelperrin is currently working on porting the solution from DoctrineBundle to this bundle: https://github.com/doctrine/DoctrineMongoDBBundle/pull/441#issuecomment-348694857

**Comment by seqq** [comment]
Sorry ) No news about PR?

**Comment by michaelperrin** [comment]
@seqq I am sorry I am still working on it and it should be ready soon!

**Comment by seqq** [comment]
great to hear, thank you!

**Comment by xorik** [comment]
@seqq you can use my code, just put it in your namespace. It works perfectly

**Comment by malarzm** [comment]
@michaelperrin any news? :)

**Comment by michaelperrin** [comment]
@malarzm I am so sorry for the delay, life took over this ;)
I could push a WIP PR if needed, which is a port of the ORM counterpart, but which is not finished yet. I keep you posted by the end of the week.

**Comment by malarzm** [comment]
@michaelperrin no worries at all! Please push the WIP, if you could highlight what is left to do maybe someone will be able to help :)

**Comment by Iar0** [comment]
made it work following https://github.com/doctrine/DoctrineMongoDBBundle/pull/448/files and the code of @xorik

**Comment by michaelperrin** [comment]
@malarzm Sorry again for the delay, here is the WIP PR: #449 . I hope to work on it again soon!

**Comment by back-2-95** [comment]
Is this related to the exception I'm getting:

```
Cannot autowire service "App\Repository\TestRepository": argument "$uow" of method "Doctrine\ODM\MongoDB\DocumentRepository::__construct()" references class "Doctrine\ODM\MongoDB\UnitOfWork" but no such service exists.
```

I'm using Symfony 4 with DoctrineMongoDBBundle and trying to set up a simple Document + RepositoryClass using annotations.

**Comment by alcaeus** [comment]
> Is this related to the exception I'm getting

Yes. ODM repositories are not suited for autowiring (yet).

**Comment by alcaeus** [comment]
See #473.
