### ISSUE TITLE
Does Symfony 4 support and documentation planned?

### ISSUE THREAD

**Issue by oriole9g** [doctrine/DoctrineMongoDBBundle#447]
I have found documentation for Symfony 3 but absolutely nothing for Symfony 4.

**Comment by malarzm** [comment]
FWIW bundle works with Symfony 4 and even has a [flex recipe](https://github.com/symfony/recipes-contrib/tree/master/doctrine/mongodb-odm-bundle/3.3)

**Comment by oriole9g** [comment]
An specifically documentation for Symfony 4 like this http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html could be an incredible help for new users. 

However, it is very good to know that it's ready and that I only need to investigate how to make it work, thanks! :)

**Comment by malarzm** [comment]
@oriole9g if you'd be willing to put together some instructions or insights and make a PR out of it, it'd be much appreciated! :)

**Comment by oriole9g** [comment]
Sure, I can write it something!

I can understand how it works when I do it in the old way creating a Controller that extends the Controller class, but when I use the Symfony 4 best practices extending from the AbstractController I do not undestand how inject the service, just type-hint an argument doesn't do the trick.

**Comment by malarzm** [comment]
Auto-wiring support will be released with 3.5.0, for the time being you need to fall back to classic DI definition

**Comment by oriole9g** [comment]
I can confirm that using dev-master works the alias for auto-wiring, 3.5 will be a big deal :)
I can write some documention and make a PR for 3.5.

**Comment by etshy** [comment]
Got a problem related to ODM installation.
I tried to install the master branch of the bundle, but it asks for `ext-mongo ^1.6.7`
Is it the mongo extension of the mongodb extension ?
this one : https://pecl.php.net/package/mongo
or this one : https://pecl.php.net/package/mongodb

ps : I'm developing on a windows, with PhpStorm and I have to install them but I have no idea how to install ext on windows >.>

**Comment by jmikola** [comment]
@etshy: In the future, please open a new issue instead of replying to an existing, unrelated thread. For future reference, instructions for installing the [`mongodb`](https://pecl.php.net/package/mongodb) extension on Windows are found in the [extension's PHP.net documentation](http://php.net/manual/en/mongodb.installation.windows.php). As you likely realized, the [`mongo`](https://pecl.php.net/package/mongo) extension is deprecated and does not support PHP 7.

**Comment by etshy** [comment]
Yeah sorry, as my problem was related to the lack of documentation for symfony4 and this module I thought it would be good to not open new issue and use this one.

**Comment by malarzm** [comment]
@etshy there's a note about PHP 7 by the end of [Install the bundle with Composer](http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#install-the-bundle-with-composer)

**Comment by oriole9g** [comment]
#448

**Comment by robinkoikkara** [comment]
I am using this bundle with symfony4. I not able to get the repository using $em->getRepository('AppBundle:xxxxxx') (no bundle ). How can i handle this situation

**Comment by malarzm** [comment]
@robinkoikkara `$em` sounds you'd be using ORM. Next if you don't have a bundle then using `AppBundle:` doesn't sound right. Last you can call `$dm->getRepository(SomeDocument::class)` and get the repository (given `SomeDocument` is mapped).

**Comment by robinkoikkara** [comment]
@malarzm Thank you . Its my mistake. They clearly mentioned in their documentation " The AcmeStoreBundle:Product string is a shortcut you can use anywhere in Doctrine instead of the full class name of the document (i.e. Acme\StoreBundle\Document\Product). As long as your document lives under the Document namespace of your bundle, this will work."

**Comment by jieranzhi** [comment]
@oriole9g did you make it work with symfony 4? can you share your experience? thanks

**Comment by alcaeus** [comment]
Closing here. This bundle works with Symfony 4, other issues (#462, #443) are tracked separately.
