### ISSUE TITLE
MONGODB ATLAS CONNECTION ISSUE

### ISSUE THREAD

**Issue by miljojohn** [doctrine/DoctrineMongoDBBundle#452]
I am trying to use mongodb atlas in my application.I set up my .env file like 

###> doctrine/mongodb-odm-bundle ###
MONGODB_URL=mongodb+srv://testuser:yyyyxyxyyx@cluster0-xcz.mongodb.net
MONGODB_DB=db_XYZ
###< doctrine/mongodb-odm-bundle ###
But i got one uri parse error.
**Failed to parse MongoDB URI: 'mongodb://mongodb+srv://xxxxx:yyyyyyyyy@cluster0-xyz.mongodb.net**

Please help .

**Comment by miljojohn** [comment]
**mongodb://mongodb+srv**://xxxxx:yyyyyyyyy@cluster0-xyz.mongodb.net

**Comment by malarzm** [comment]
Looking at [examples in the documentation](https://docs.atlas.mongodb.com/driver-connection/#php-driver-example) your URI looks weird.

**Comment by miljojohn** [comment]
I am able to connect  mongodb 3.6 from  php code . I am trying to connect the same Connection string from symfony DoctrineMongoDBBundle configuration.

My php code which is working perfectly mentioned below.
<?php
require 'vendor/autoload.php';


try{
$con = new MongoDB\Client("mongodb+srv://testuser:testpassword@cluster0-324234.mongodb.net");
echo ("Connection OK");

$db = $con->db_xxxxx;

// Creating Document  
$collection = $db->TechcthreeConnectivitytest;

echo ("connected to database properly");
// Insering Record  
$collection->insertOne( [ 'name' =>'MILJO JOHN KODIYAN', 'email' =>'miljo@techcthree.com' ] );
// Fetching Record  
echo ("Inserted properly");

}catch(Exception $exp) {

echo($exp);

}
?>


But while using  Doctrinemongodbbundle connection string is appended with another mongodb://

**Comment by malarzm** [comment]
Ok this seems like a bug then. At a glance I don't see anything in the bundle that would be prepending URI with additional `mongodb://`, can you please share what driver are you using? Is this legacy `mongo` or new `mongodb` + adapter?

**Comment by miljojohn** [comment]
I am using 3.6 and i am able to connect the mongodb atlas using new MongoDB\Client

 $con = new MongoDB\Client("mongodb+srv://testuser:testpassword@cluster0-324234.mongodb.net");
I am attaching the php file which is working perfectly .
[phpconnection.txt](https://github.com/doctrine/DoctrineMongoDBBundle/files/1774462/phpconnection.txt)

From symfony i tried with  the connection string for  3.4 mongodb version and its working fine. 

Thanks a lot.

**Comment by malarzm** [comment]
Ok, found the issue in the adapter, gonna open an issue there and cross reference.

**Comment by alcaeus** [comment]
@miljojohn would you mind testing `dev-master` of `mongo-php-adapter`? I've merged the changes and will tag a new release later today.

**Comment by alcaeus** [comment]
@miljojohn the 1.1.5 release of `mongo-php-adapter` fixes the handling of `mongodb+srv` connection URLs. If the problem persists, please open an issue there. Thanks!

**Comment by miljojohn** [comment]
message":"Cannot create SSL client. SSL is not enabled in this  build.", "class":" MongoDB\\ Driver\\ Exception\\ InvalidArgumentException (in symfony )
I can run the same with php  https://github.com/doctrine/DoctrineMongoDBBundle/files/1774462/phpconnection.txt

mongodb
////////////
MongoDB support => enabled
MongoDB extension version => 1.5.0-dev
MongoDB extension stability => devel
libbson bundled version => 1.9.2
libmongoc bundled version => 1.9.2
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => disabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled

**Comment by alcaeus** [comment]
While not good, the error points out that `ext-mongodb` was built without SSL support. How did you install the driver?

**Comment by miljojohn** [comment]
pecl install mongodb
$ echo "extension=mongodb.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

Installed ext-mongodb using this command and also i am able to connect the atlas server from normal php on the same server. Please refer this code https://github.com/doctrine/DoctrineMongoDBBundle/files/1774462/phpconnection.txt

**Comment by miljojohn** [comment]
MongoDB support => enabled
MongoDB extension version => 1.4.2
MongoDB extension stability => stable
libbson bundled version => 1.9.3
libmongoc bundled version => 1.9.3
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => disabled
libmongoc SASL => enabled
libmongoc compression => enabled
libmongoc compression snappy => disabled
libmongoc compression zlib => enabled 


this is my configuration but still i am getting error like message":"**Cannot create SSL client. SSL is not enabled in this build.","class":"MongoDB\\Driver\\Exception\\InvalidArgumentException**"

**Comment by jmikola** [comment]
The exception with message "Cannot create SSL client. SSL is not enabled in this build." originates in [`phongo_manager_init()`](https://github.com/mongodb/mongo-php-driver/blob/1.4.2/php_phongo.c#L2328) when `MONGOC_ENABLE_SSL` is not defined.

In the same file, [`PHP_MINFO_FUNCTION(mongodb)`](https://github.com/mongodb/mongo-php-driver/blob/1.4.2/php_phongo.c#L2865) also checks whether `MONGOC_ENABLE_SSL` is defined to report "libmongoc SSL" for `phpinfo()` output.

The formatting of the `phpinfo()` output you've shared numerous times in this thread indicates that you obtained it from a CLI process. I'm reasonably certain that if you checked the `phpinfo()` output from the same PHP environment that is yielding the "Cannot create SSL client." error, you'd find that "libmongoc SSL" is not enabled.

It's entirely possible to have multiple versions of PHP installed on the same system. This is often the case for MacOS users, where they might have the default version of PHP that ships with MacOS, a version available with MAMP, and/or a PHP runtime installed with Homebrew. In the future, this is all helpful information that you should provide in a support request. AFAIK, you've provided no details whatsoever about your operating system or PHP environment.

> ```
> pecl install mongodb
> echo "extension=mongodb.so" >> php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"
> ```

The second line in the command above is only adding "extension=mongodb.so" to the INI file used by the `php` CLI command. You should understand that each PHP SAPI (e.g. CLI, web) may have its own INI file, which will need "extension=mongodb.so" added to function properly.

I assume you copied that snippet from the [PHP library](https://github.com/mongodb/mongo-php-library#installation) or [driver](https://github.com/mongodb/mongo-php-driver#installation) README files. Both of those also link to [Installing the MongoDB PHP Driver with PECL](https://secure.php.net/manual/en/mongodb.installation.pecl.php) on PHP.net, which talks about each PHP environment possibly having its own `pecl` command and `php.ini` files.

You should confirm exactly which PHP environment is producing this exception, and then walk through installation steps for that exact environment. Assuming that environment has its own `pecl` command and `php.ini` file, those should be used for installation.

**Comment by miljojohn** [comment]
thank you @jmikola  . Issue is fixed.
