### ISSUE TITLE
The authMechanism 'X509' does not exist

### ISSUE THREAD

**Issue by chrispindjako** [doctrine/DoctrineMongoDBBundle#453]
Hi, I'm using symfony 3.2 with MongoDB 3.4 and in my DoctrineMongoDBBundle 3.4.1 configuration file 
the parameter authMechanism is present with value X509. My problem is that when I try to connect to my Mongo Database i received  this error:  {"code":500,"message":"The authMechanism 'X509' does not exist."}

My DoctrineMongoDBBundle configuration file is below:

![sans titre](https://user-images.githubusercontent.com/16692562/37616435-cbd703ce-2ba7-11e8-93f1-ec4e8344d07e.png)

And my associate servIce to this config file is :

![sans titre](https://user-images.githubusercontent.com/16692562/37616568-489e45de-2ba8-11e8-8b73-e12c90cfba45.png)
Can you help me please to fix this isssue?

**Comment by jmikola** [comment]
> `{"code":500,"message":"The authMechanism 'X509' does not exist."}`

While this may be the response from your web application, we'll need to see the actual PHP exception from which this error originated (its class name, error message, and error code). Additionally, a condensed stack trace going back to the function that threw the exception will be helpful.

Separate from that, details about your MongoDB environment (e.g. [`buildInfo`](https://docs.mongodb.com/manual/reference/command/buildInfo/) command output) and PHP environment (e.g. [`phpinfo()`](http://php.net/manual/en/function.phpinfo.php) output) will be helpful.

**Comment by chrispindjako** [comment]
Here are the informations you asked me:

     -**symfony dev.log**:
![symfony_log_dev](https://user-images.githubusercontent.com/16692562/37662872-f02d0054-2c4f-11e8-9ad2-9ba7dcb9109d.png)

     -**mongodb buildInfo**
![mongodb_info](https://user-images.githubusercontent.com/16692562/37662941-141b6ae6-2c50-11e8-9c4d-1141205ac7ee.png)

     -**php info**:
[phpinfo.txt](https://github.com/doctrine/DoctrineMongoDBBundle/files/1829892/phpinfo.txt)

_thank you in advance_

**Comment by jmikola** [comment]
It looks like that exception message originates in the [`mongo_store_option()`] function (https://github.com/mongodb/mongo-php-driver-legacy/blob/1.6.16/mcon/parse.c#L403) in the legacy "mongo" extension.

"X509" is not actually a supported value for the [`authMechanism` URI option](https://docs.mongodb.com/manual/reference/connection-string/#urioption.authMechanism). The correct value is "MONGODB-X509", which is what we see in the MongoDB manual and aforementioned extension function.

Looking at ['MongoClient::__construct()`](http://php.net/manual/en/mongoclient.construct.php), I believe this is just a documentation issue. I just corrected this in http://svn.php.net/viewvc?view=revision&revision=344543, so the change should be appear on PHP.net in the coming days.

**Comment by chrispindjako** [comment]
Thanks a lot, the php documentation has been updated. What action can I take now?

**Comment by jmikola** [comment]
If you intend to use the [X509 authentication mechanism](https://docs.mongodb.com/manual/tutorial/configure-x509-client-authentication/), you should specify `MONGODB-X509` for the `authMechanism` URI option.

**Comment by malarzm** [comment]
Closing since #454 was merged
