### ISSUE TITLE
How to include MongoDB embedded documents in Symfony forms ?

### ISSUE THREAD

**Issue by aturki** [doctrine/DoctrineMongoDBBundle#459]
Hi all,

This is more of a feature request than a bug. To my knowledge, Embedded documents (Either single or multiple) are not supported in Symfony forms the way Referenced documents are. Is this something on the current roadmap ?

**Comment by malarzm** [comment]
@aturki please elaborate on what you'd expect. Using embedded forms to edit embedded documents (or a collection type for `EmbedMany`) is working fine :)
