### ISSUE TITLE
Fixtures are not loaded as services

### ISSUE THREAD

**Issue by buffcode** [doctrine/DoctrineMongoDBBundle#461]
According to the [Symfony docs](https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html#accessing-services-from-the-fixtures):
> Your fixtures class is a service, so you can use normal dependency injection

This is currently only true for ORM but not ODM, as this bundle will always instantiate the fixture using `Doctrine\Common\DataFixtures\Loader::createFixture()`.

I would expect that the bundle behaves identical to the ORM part: fixtures that are configured as services are picked up by the CompilerPass and passed to the loader. This loader should be used by the command to trigger fixtures.

A temporary workaround is to implement `ContainerAwareInterface` and use `$this->get(...)` but that is limited to public services.

**Comment by alcaeus** [comment]
The fixture loader used for MongoDB ODM does not yet allow using services as fixtures. We simply haven't gotten to it yet. If you ware willing to implement it, we'd be happy to accept a contribution and help out. You can use https://github.com/doctrine/DoctrineFixturesBundle/pull/209 for guidance.

**Comment by buffcode** [comment]
I though about this, but I suspect will be a major BC.
Currently the docs recommend to extend from `Doctrine\Bundle\FixturesBundle\Fixture` which implements `ORMFixtureInterface`. This interface is autoconfigured to be loaded by the *ORM* command, as such having a *ODM* fixture and then executing `doctrine:fixtures:load` will most likely fail with `The class '...' was not found in the chain configured namespaces`.

I see two possibilities, preferring no. 1:
1. Re-factor the DoctrineFixtures bundle to be agnostic about the ORM/ODM part. To implement fixture-as-a-service the commands from both packages will likely be 90% duplicates so probably this makes sense. As this bundle depends on the DoctrineFixturesBundle for the fixtures functionality, the own command (`doctrine:mongodb:fixtures:load`) could then be dropped/deprecated.

2. Copy&paste all functionality from the DoctrineFixturesBundle such as loader, compiler, command etc. but replace relevant ORM parts with their ODM counterparts. Existing fixtures will have to implement another interface in order to be picked up by the autoconfiguration.

What do you think?

**Comment by arendjantetteroo** [comment]
Just got caught by this after seeing the nice --group feature blog about v3.1 of the orm version and thinking this would work on the mongo part as well. 

I can take a stab at this if still usefull. I also saw the ticket about makng it a seperate bundle. Does it make sense to first try to get this working on the 1.x branch? I assume that the fact the object manager implementation changes in 2.0 should not matter for the fixture loading right?

**Comment by alcaeus** [comment]
If you want to give the implementation a shot, please be my guest. If we're going to have a 3.6 release then I'd like to offer it in there as well, but I'm not sure if it's necessary (only if we need to deprecate more things for 4.0).

You can start working on this in a 4.0 branch and we'll take care of the rest if we're going to put it into 3.x.
