### ISSUE TITLE
Symfony 4 - MongoDbSessionHandler type hint \MongoDB\Client

### ISSUE THREAD

**Issue by tniemann** [doctrine/DoctrineMongoDBBundle#462]
hi,

in Symfony 4 the MongoDbSessionHandler requires \MongoDB\Client as constructor argument.
Currently the integration via Symfony 4 is as follow:

`mongo:
        class: Mongo
        factory: ["@mongo.connection", getMongo]`

The problem here is that **getMongo** returns **MongoClient** which breaks the code.
Is there a fix plant in the next weeks?

Regards
Thomas

**Comment by alcaeus** [comment]
Ah, good point. If you want to take a shot at fixing it, go ahead - otherwise it will have to wait until one of us maintainers has the time do fix it.

**Comment by alcaeus** [comment]
Closing here. With 4.0, this will easily be possible by getting the `Client` object from the Document manager, similar to how the current connection object is fetched.
