### ISSUE TITLE
No paginator in this bundle ?

### ISSUE THREAD

**Issue by etshy** [doctrine/DoctrineMongoDBBundle#463]
I just wanted to know why there is a Paginator functionnality in the ZF Module but not in the Symfony Bundle ?

**Comment by alcaeus** [comment]
Sorry for the late reply.The answer is simple: Zend Framework ships a pagination, so it makes sense to ship an adapter. With Symfony there is no pagination component, so there's nothing we could ship an adapter for. Other pagination components (e.g. Pagerfanta) contain adapters to paginate ODM query builders, so there are plenty of alternatives.

**Comment by etshy** [comment]
Oh so that's why.

I ended up using knp Paginator, I don't know if it's the best but that was the first I found back then for ODM/symfony

Thanks for the answer anyways.
