### ISSUE TITLE
No bundle AppBundle was found

### ISSUE THREAD

**Issue by mooncool** [doctrine/DoctrineMongoDBBundle#465]
When I use symfony 4, I run command `bin/console doctrine:mongodb:generate:documents AppBundle`, it said: `Bundle "AppBundle" does not exist or it is not enabled.`. I think `AppBundle` is an alias for `src` folder, what's wrong?

**Comment by jwage** [comment]
Hi, this is not an issue related to this bundle. Sounds like your Symfony app is not configured right. You need to enable and configure AppBundle.

**Comment by redayoub** [comment]
@mooncool I have the same issue, did you find a solution?
