### ISSUE TITLE
Problem with composer update (install is working fine)

### ISSUE THREAD

**Issue by etshy** [doctrine/DoctrineMongoDBBundle#478]
Like the title said, I have a problem with the `composer update`

Here is the output

```
[Composer\DependencyResolver\SolverProblemsException]
  Problem 1
      - The requested package doctrine/mongodb-odm-bundle could not be found in any version, ther
  e may be a typo in the package name.

  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to your minimum-stability
  setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
   - It's a private package and you forgot to add a custom repository to find it

  Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

and my composer.json (doctrine related parts only, to not have too much lines)
```
{
    ...
    "require": {
        "php": "^7.2",
        "alcaeus/mongo-php-adapter": "^1.1@dev",
        "doctrine/mongodb-odm-bundle": "^3.5",
        "stof/doctrine-extensions-bundle": "^1.3@dev",
        ...
    },
    "minimum-stability": "dev",
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "platform": {
            "ext-mongo": "1.6.16"
        }
    },
    ...
}
```

I don't really want to change the `"doctrine/mongodb-odm-bundle": "^3.5",` to `"doctrine/mongodb-odm-bundle": "dev-master",`, If I'm not mistaken, the master is now the v4.0 alpha, right? I don't know if my project is ready to upgrade to 4.0.

the weird thing is the `install` is working perfectly. I just have to delete the vendor and composer.lock and run `composer install`.

I don't really know where the problem may come from, so I made this issues to have some help.

**Comment by alcaeus** [comment]
You don't want to switch to dev-master. You can switch to `^4.0.0@alpha` if you're brave, but I don't recommend doing that for production at the moment.

As for the update issue, is there more to this error message? This sounds almost like some other constraint prevents a successful upgrade, for whatever reason. I've noticed this at times with `mongo-php-adapter`, but the fix to that was to add `config.platform.ext-mongo`, so I'm not sure where this is coming from.

**Comment by etshy** [comment]
just tried again, I got the `Nothing to install or update` now that I deleted and re-install al my dependencies.

I don't remember anything more in the error message and I have already the `config.platform.ext-mongo` (cf my composer.json, it's set to `1.6.16`)

**Comment by alcaeus** [comment]
Let's call it a hiccup then - please reopen with more information if the issue appears again.
