### ISSUE TITLE
CommandDataCollector 

### ISSUE THREAD

**Issue by blixit** [doctrine/DoctrineMongoDBBundle#488]
I'm trying to use the DoctrineMongoDBBundle  with symfony4.
After the bundle installation, 
`composer require doctrine/mongodb-odm-bundle`
I got this error: 

Compile Error: Declaration of `Doctrine\Bundle\MongoDBBundle\DataCollector\CommandDataCollector::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Throwable $exception = NULL) `
must be compatible with `Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface::collect(Symfony\Component\HttpFoundation\Request $request, Symfony\Component\HttpFoundation\Response $response, ?Exception $exception = NULL)`

This error can be fixed by changing **Throwable** by **Exception**.

**Comment by malarzm** [comment]
Indeed, the [signature contains `Exception` for 6 years now](https://github.com/symfony/symfony/blame/cbe289517470eeea27162fd2d523eb29c95f775f/src/Symfony/Component/HttpKernel/DataCollector/DataCollectorInterface.php#L28), mind sending us a PR? :)

**Comment by blixit** [comment]
> Indeed, the [signature contains `Exception` for 6 years now](https://github.com/symfony/symfony/blame/cbe289517470eeea27162fd2d523eb29c95f775f/src/Symfony/Component/HttpKernel/DataCollector/DataCollectorInterface.php#L28), mind sending us a PR? :)

Of course. let me fork the project.

**Comment by alcaeus** [comment]
We need to check some more classes - #484 added doctrine/coding-standard which requires using `Throwable` instead of `Exception`.

**Comment by alcaeus** [comment]
Yes please! 👍

**Comment by jcaillot** [comment]
Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface interface changed (again) with the 5.0 version !

we have got :

Symfony 4.2

` public function collect(Request $request, Response $response, \Exception $exception = null);
 `
https://github.com/symfony/symfony/blob/4.2/src/Symfony/Component/HttpKernel/DataCollector/DataCollectorInterface.php


Symfony 4.3 and 4.4

`public function collect(Request $request, Response $response/*, \Throwable $exception = null*/);`

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/HttpKernel/DataCollector/DataCollectorInterface.php


Symfony 5.0

`public function collect(Request $request, Response $response, \Throwable $exception = null);`

https://github.com/symfony/symfony/blob/5.0/src/Symfony/Component/HttpKernel/DataCollector/DataCollectorInterface.php

**Comment by alcaeus** [comment]
See https://github.com/doctrine/DoctrineMongoDBBundle/pull/604 - 4.1.0 with a fix will be out shortly.
