### ISSUE TITLE
Invalid array key

### ISSUE THREAD

**Issue by zaerl** [doctrine/DoctrineMongoDBBundle#494]
On [DoctrineMongoDBExtension::normalizeDriverOptions:319](https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/DependencyInjection/DoctrineMongoDBExtension.php#L319) we have `typemap` (as well as on all tests) but on `ext-mongodb` `Client` class constructor the key is `typeMap`. This generate various problems with `array` type hints on `Doctrine\ODM\MongoDB\UnitOfWork:getOrCreateDocument` for example which expect an array but get a `MongoDB\Model\BSONArray` (which is the default and is not an array).

A var_dump of generated option:
```
Array
(
    [typemap] => Array
        (
            [root] => array
            [document] => array
        )
    [typeMap] => Array
        (
            [array] => MongoDB\Model\BSONArray
            [document] => MongoDB\Model\BSONDocument
            [root] => MongoDB\Model\BSONDocument
        )
)
```
Change row 319 to:
```
$driverOptions['typeMap'] = ['root' => 'array', 'document' => 'array'];
```
and the problem is solved.

**Comment by jmikola** [comment]
@alcaeus: This does look like a typo in the bundle. The correct option name is [`typeMap`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBClient__construct/) in `$driverOptions`.

**Comment by zaerl** [comment]
Thanks.
