### ISSUE TITLE
how to generate document whith symfony 4.1

### ISSUE THREAD

**Issue by christiankasse** [doctrine/DoctrineMongoDBBundle#498]
how to generate a **document** with symfony 4.1 I am given the error saying **#`Bundle "App" does not exist or it is not enabled`.**

**Comment by malarzm** [comment]
The command is no longer supported, please see #479 for more details

**Comment by christiankasse** [comment]
which command will I use to generate documents for my database because `** #php bin/console doctrine:generate:mongodb:document**` don't work

**Comment by christiankasse** [comment]
what will I do then in this case?

**Comment by christiankasse** [comment]
what will I do then in this case?

**Comment by jmikola** [comment]
https://github.com/doctrine/DoctrineMongoDBBundle/issues/479#issuecomment-426149593 explains that the ODM project will no longer maintain a command to generate document classes. This is something that can be implemented in Symfony's [MakerBundle](https://github.com/symfony/maker-bundle) if others are willing to contribute towards building that functionality.

The most immediate solution is to create your model classes on your own, as you would any other PHP file. The [Basic Mapping](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/basic-mapping.html#basic-mapping) documentation is a good starting point for that.

**Comment by christiankasse** [comment]
I apologize but I can not work with ODM because I have left a way out that I have been told to work on, can you help me by explaining what to do? now because I'm totally stuck, please

**Comment by etshy** [comment]
I don't know what was generated with the Document  generation, but you can just create your class and use ODM annotation.

```
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;

...

    /**
     * @var string|null
     * @ODM\Field(type="string")
     * @Assert\Type("string")
     */
    protected $name;
```

The `@Assert` is for form validation, you can ignore it if you don't use that. 

I never had problem doing the Documents by myself (I didn't even know we could generate them before the announcement of dropping this feature).

**Comment by jmikola** [comment]
In addition to what @etshy shared, you'll also find some example of annotated document classes in the [sandbox](https://github.com/doctrine/mongodb-odm/tree/master/tools/sandbox) directory of the main ODM repository. Keep in mind that the sandbox demonstrates how to use ODM outside of a framework, so the configuration bits will look different and won't be relevant if you're using Symfony and the bundle; however, the mapped document classes are still relevant and can serve as examples.

**Comment by Alsatian67** [comment]
> I don't know what was generated with the Document generation, but you can just create your class and use ODM annotation.

The command was generating accessors for each properties with `@ODM\Field` annotation.

This can be very cumbersome to do manually, when a document contains lots of fields.


No "Symfony Maker" solution end 2019 ?

**Comment by malarzm** [comment]
> The command was generating accessors for each property marked with @ODM\Field annotation.
> This can be very cumbersome to do manually, when a document contains lots of fields.

This can be done in any decent IDE with a few keystrokes.

> No "Symfony Maker" solution end 2019 ?

Please open an issue in the [Symfony Maker repo](https://github.com/symfony/maker-bundle) and ask for document generation there. Asking this question here will not let maker maintainers aware the feature is anticipated.
