### ISSUE TITLE
how to generate repositories using symfony 4.1

### ISSUE THREAD

**Issue by christiankasse** [doctrine/DoctrineMongoDBBundle#503]
I'm a bit stuck and I do not know **how I can generate the repository** with symfony 4.1 as long as it's me alone that generates the getters and setters

**Comment by malarzm** [comment]
It's the same case as with generating documents (https://github.com/doctrine/DoctrineMongoDBBundle/issues/498), ODM is dropping code-generation commands. Until this is somehow possible with MakerBundle, you need to write code by hand.

**Comment by etshy** [comment]
You just have to create a class that extends `Doctrine\ODM\MongoDB\DocumentRepository` and "link" it to your Document with the Annotation `@ODM\Document(repositoryClass="yourRepoClass")`

That's well explained on the [docs](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/document-repositories.html#custom-repositories)

**Comment by christiankasse** [comment]
`
use App\Repository\ProductRepository;

/**
     * @Route("/show/{id}", name="show.home")
     */
    public function showAction($id, DocumentManager $dm){

	    $product = $dm->getRepository(ProductRepository::class)->find($id);

	    if (!$product) {

	        throw $this->createNotFoundException('No product found for id '.$id);
	    }

	    return $this->render('home/show.html.twig', [
            'controller_name' => 'HomeController',
        ]);
	}`

when I try to pass the id in parameter, I am informed that the  repository class  is not found and I understand nothing while I just imported it

**Comment by christiankasse** [comment]
**Help Please**

**Comment by etshy** [comment]
I don't use Repository like that, but when you do `getRepositorty()` you need to pass the Entity  FQCN, not the Repository FQCN.

As stated in the [docs](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/document-repositories.html)

`$repository = $documentManager->getRepository(User::class);`

You should read more the documentation, all your questions until now was answered there.
