### ISSUE TITLE
Call to a member function getUnitOfWork() on null when using ServiceDocumentRepository in Symfony 4

### ISSUE THREAD

**Issue by adityarai** [doctrine/DoctrineMongoDBBundle#504]
```php
<?php

namespace App\Repository;

use App\Document\HtmlView;
use Doctrine\Bundle\MongoDBBundle\Repository\ServiceDocumentRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * @method HtmlView|null find($id, $lockMode = null, $lockVersion = null)
 * @method HtmlView|null findOneBy(array $criteria, array $orderBy = null)
 * @method HtmlView[]    findAll()
 * @method HtmlView[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class HtmlViewRepository extends ServiceDocumentRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, HtmlView::class);
    }
}
```

**Comment by alcaeus** [comment]
Please provide additional information, e.g. the version of the bundle you are using and a full trace for the exception in question. The information you provided is not sufficient to take a look at this.

**Comment by adityarai** [comment]
Bundle version is 
"alcaeus/mongo-php-adapter": "^1.1",
"doctrine/mongodb-odm-bundle": "^3.5",

controller Action:
`/**
     * @Route("/", name="html_view_index", methods="GET")
     */
    public function index(HtmlViewRepository $htmlViewRepository): Response
    {
        return $this->render('html_view/index.html.twig', ['html_views' => $htmlViewRepository->findAll()]);
    }`

![call to a member function getunitofwork on null 500 internal server error](https://user-images.githubusercontent.com/1521692/49207539-39541800-f3db-11e8-8569-a88f26bd386a.png)

**Comment by stof** [comment]
@adityarai FYI, a much better way to provide the stack trace in a bug report is to switch to the `Stack Trace` tab on that error page, which provides the stack trace in a plain-text format (which can be copy-pasted in the issue)

**Comment by alcaeus** [comment]
That’s a good point - I’ll add a nice exception message to the trait to make spotting these issues easier.

**Comment by adityarai** [comment]
![call to a member function getunitofwork on null 500 internal server error 1](https://user-images.githubusercontent.com/1521692/49215106-06ffe600-f3ee-11e8-870a-474d8fee68d4.png)

**Comment by adityarai** [comment]
Symfony version is 4.1.8 

In the service.yaml:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: ["@doctrine_mongodb"]
        tags:
        - { name: "request.param_converter", converter: "doctrine.odm" }

**Comment by adityarai** [comment]
In doctrine_mongodb.yaml
doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: App\Document\
                    alias: App

removed doctrine_mongo_db_param_converter from service as it was not needed. The error still remains. 

In doctrine.yaml
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

**Comment by alcaeus** [comment]
The config looks good - only issue I can imagine is that the config declares you use annotations when you didn't - can you confirm you indeed map your changes using annotations, not yaml or XML?

**Comment by adityarai** [comment]
@alcaeus everything is mapped using annotations.. 
Updated doctrine/mongodb-odm-bundle (3.5.0 => 3.5.1), now the error shows:
![mongo](https://user-images.githubusercontent.com/1521692/49526275-805b7500-f8d5-11e8-9d97-cede2fd7e14a.png)

**Comment by adityarai** [comment]
`<?php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB,
    Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique as MongoDBUnique,
    Symfony\Component\Validator\Constraints as Assert;

/**
 * User Table
 *
 * @MongoDB\Document(collection="__HTML_VIEW__", repositoryClass="App\Repository\HtmlViewRepository")
 * @MongoDBUnique(fields="title")
 */
class HtmlView
{
    /**
     * @MongoDB\Id
     */
    private $id;

    /**
     * @MongoDB\Field(type="string")
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @MongoDB\Field(type="string")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @MongoDB\Field(type="date")
     */
    private $createdOn;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->createdOn = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getCreatedOn()
    {
        return $this->createdOn;
    }

    /**
     * @param mixed $createdOn
     */
    public function setCreatedOn($createdOn): void
    {
        $this->createdOn = $createdOn;
    }


}
`

**Comment by alcaeus** [comment]
@adityarai missed the last sentence of your previous comment until now. Do you use ORM and ODM at the same time?

**Comment by adityarai** [comment]
Only ODM.. ORM is active though but its not being used to create any DB instance...

**Comment by alcaeus** [comment]
This took way longer than I'd like to admit, but can you try changing the type hint for the `$registry` argument from `Symfony\Bridge\Doctrine\RegistryInterface` to `Doctrine\Bundle\MongoDBBundle\ManagerRegistry`?

The registry provided by the ODM bundle doesn't implement that interface, which is why an ORM registry is injected. The documentation also specifies using the bundle registry, not the generic interface from the doctrine-bridge. Did you maybe copy an ORM service repository and forget changing the typehint?

**Comment by adityarai** [comment]
Its working now,...  Changed registry from Symfony\Bridge\Doctrine\RegistryInterface to Doctrine\Bundle\MongoDBBundle\ManagerRegistry.

The other problem is,  I still have to add this service for param converter, else if removed the document displays null result:
doctrine_mongo_db_param_converter:
        class: Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\DoctrineParamConverter
        arguments: ["@doctrine_mongodb"]
        tags:
        - { name: "request.param_converter", converter: "doctrine.odm", priority: 1 }

example:
``/**
     * @Route("/{id}/edit", name="html_view_edit", methods="GET|POST")
     */
    public function edit(Request $request, HtmlView $htmlView): Response
    {
        dump($htmlView);die;
    }``
displays null

**Comment by alcaeus** [comment]
> Thanks.. Its working now,... Changed registry from Symfony\Bridge\Doctrine\RegistryInterface to Doctrine\Bundle\MongoDBBundle\ManagerRegistry.

Great!

> The other problem is, I still have to add this service for param converter, else if removed the document displays null result:

Please create a feature request - don't know how that slipped through the cracks.

> And Also latest version of symfony shows this exception when displaying id in twig file:

That's not a problem with this library - please use StackOverflow or create an issue with Twig or Symfony depending where the problem arises. Thanks.
