### ISSUE TITLE
Symfony 4.2 deprecation : A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

### ISSUE THREAD

**Issue by arendjantetteroo** [doctrine/DoctrineMongoDBBundle#507]
It seems the bundle currently uses a builder without a root node.

**Comment by alcaeus** [comment]
The tree builder deprecation is already fixed in 3.5.1 and will be fixed in 2.0.0-Beta1 which should be coming in a few days as well.
