### ISSUE TITLE
Extract fixture loading command to separate bundle

### ISSUE THREAD

**Issue by alcaeus** [doctrine/DoctrineMongoDBBundle#509]
To better separate concerns and keep track of dependencies, we should extract the `LoadDataFixturesDoctrineODMCommand` to a separate bundle and release it as a separate package (comparable to DoctrineBundle and DoctrineFixturesBundle).

**Comment by malarzm** [comment]
While reason is plausible, I'm not sure extracting a single command to a bundle is the best course of action. 

Offhand, https://github.com/doctrine/DoctrineFixturesBundle is mentioning ODM in the readme, does that bundle support ODM already?

**Comment by jwage** [comment]
Yes, I believe so.

**Comment by alcaeus** [comment]
At the moment, the bundle does not support ODM - I'll check if it can easily be changed to do so. The reason I want to extract it is to have a purpose-built bundle that integrates mongodb-odm and data-fixtures. At this stage, you see the command but can't run it unless you know that you have to require data-fixtures as well.

**Comment by GromNaN** [comment]
I don't think it's useful to extract the code related to fixtures into a separate package, which would require additional maintenance work.

In any case, when a developer wants to add fixtures to their project, they must implement `Doctrine\Common\DataFixtures\FixtureInterface`; they must therefore explicitly require the `doctrine/data-fixtures` package so as not to depend on an indirect dependency.

The `doctrine:mongodb:fixtures:load` command is not available when the `doctrine/data-fixtures` package is not available. https://github.com/doctrine/DoctrineMongoDBBundle/blob/cb65826e2fdcb652e98911b1fc56e1ce736ea2a9/src/DependencyInjection/DoctrineMongoDBExtension.php#L480-L487
