### ISSUE TITLE
The class 'App\Document\User' was not found in the chain configured namespaces App\Entity

### ISSUE THREAD

**Issue by christiankasse** [doctrine/DoctrineMongoDBBundle#528]
I just changed the configuration of my security by replacing mysql by mongo instead of `App \ Entity \ User `by` App \ Document \ Use`r and I try to connect to the database with a login form but I am displayed this mistake `The class 'App\Document\User' was not found in the chain configured namespaces App\Entity`
**here is my method in the controller to check the user**

`public function getUser($credentials, UserProviderInterface $userProvider){
        $token = new CsrfToken('authenticate', $credentials['csrf_token']);
        if (!$this->csrfTokenManager->isTokenValid($token)) {
            throw new InvalidCsrfTokenException();
        }
      `  `$user = $this->dm->getRepository(User::class)->findOneBy(['email' => $credentials['email']]);`
    `
        if (!$user) {
            // fail authentication with a custom error
            throw new CustomUserMessageAuthenticationException('Email could not be found.');
        }
        return $user;
    }`

Please help

**Comment by malarzm** [comment]
The issue stems from misconfiguration - somewhere you're still referencing `App\Entity` namespace. As this is not the problem with the bundle but rather problem with your code I'd advice to post your question to https://stackoverflow.com
