### ISSUE TITLE
Update MongoDB extension specific documentation

### ISSUE THREAD

**Issue by alcaeus** [doctrine/DoctrineMongoDBBundle#533]
The [Reusing Mongo Connection](https://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#reusing-mongo-connection) chapter in the docs still uses the legacy driver methods. This needs to be rewritten to use the new MongoDB extension classes.

**Comment by malarzm** [comment]
This is duplicating #526 :)

**Comment by alcaeus** [comment]
Duplicates #526. Need to learn searching for issues first...
