### ISSUE TITLE
[Form][DocumentType] Multiple mode and remove associations

### ISSUE THREAD

**Issue by cedriclombardot** [doctrine/DoctrineMongoDBBundle#54]
When i build my form with something like that :

``` php
<?php
//.....
 $builder->add('actors', 'document', array( 'multiple' => 'true',  
'class' => 'Admingenerator\\DoctrineODMDemoBundle\\Document\\Actor',));
```

I can associate actors to my movie, but i can't remove them, do you know why ?

Note if i make a var_dump in my data class Movie

``` php
<?php
//.....
    public function setActors(\Doctrine\Common\Collections\ArrayCollection $actors)
    {
        var_dump($actors);
         $this->actors = $actors;
    }
```

the ArrayCollection is good. Bug in persist ??

**Comment by malarzm** [comment]
If this was bug in persist (which seems likely as collection was ok in document) then it is fixed in ODM for long time now. If this is not the case please feel free reopen the issue
