### ISSUE TITLE
API platform + symfony 4 + mongodb : "The repository for \"App\\Document\\User\" must be an instance of \"Doctrine\\ODM\\MongoDB\\Repository\\DocumentRepository\"

### ISSUE THREAD

**Issue by Belssem** [doctrine/DoctrineMongoDBBundle#541]

**Comment by alcaeus** [comment]
Please add more information than just the title of this issue. As is, there's nothing we can do.

**Comment by Belssem** [comment]
@alcaeus  
ok I created a document called User and i used mongodb and api platform and when i try to show the users of my database using /api/users i got "The repository for "App\Document\User" must be an instance of "Doctrine\ODM\MongoDB\Repository\DocumentRepository"." 
i've also try to create a UserRepository like this : 
`<?php
/**
 * Created by PhpStorm.
 * User: belsem
 * Date: 14/03/19
 * Time: 01:31 م
 */

namespace App\Repository;


use App\Document\User;
use Doctrine\Bundle\MongoDBBundle\Repository\ServiceDocumentRepository;
use Doctrine\ODM\MongoDB\DocumentRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

class UserRepository extends DocumentRepository
{

    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, User::class);
    }
}
`
i didn't know the origin of this problem .any help ?

**Comment by etshy** [comment]
Could you format your block code with ``` instead of `
```
Like this
on multiple line
```

In which context do you have this error ? (how do you call for `User` repository ?)
When you tried to do your own `UserRepository`, did you "linked" it to your document ?

**Comment by Belssem** [comment]
when i was trying to fetsh(get) users using /api/users i got this error.
i created myself the UserRepository but how can i related it with the document ? i will show you my code 
``now

**Comment by Belssem** [comment]
```<?php
/**
 * Created by PhpStorm.
 * User: belsem
 * Date: 14/03/19
 * Time: 01:31 م
 */

namespace App\Repository;


use App\Document\User;
use Doctrine\Bundle\MongoDBBundle\Repository\ServiceDocumentRepository;

use Doctrine\Bundle\MongoDBBundle\ManagerRegistry ;
use Doctrine\ODM\MongoDB\DocumentManager;

class UserRepository extends  ServiceDocumentRepository
{
    public function __construct(DocumentManager $dm )
    {
        $uow = $dm->getUnitOfWork();
        $classMetaData = $dm->getClassMetadata(User::class);
        parent::__construct($dm, $uow, $classMetaData);
    }
}``` 
```
<?php

namespace App\Document;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use DateTime;
use Doctrine\ORM\Mapping as ORM;


/**
 *
 * @ApiResource()
 * @MongoDB\Document(repositoryClass="App\Repository\UserRepository")
 *
 *
 *
 */
 class User
{
    /** @MongoDB\Id*/
    private $id;

    /** @MongoDB\Field(type="string") */
    private $firstname;

    /** @MongoDB\Field(type="string") */
    private $lastname;

    /** @MongoDB\Field(type="string") */
    private $email;

    /** @MongoDB\Field(type="string") */
    private $login;
    /** @MongoDB\Field(type="string") */
    private $password;
    /** @MongoDB\Field(type="int") */
    private $salary;

    /** @MongoDB\Field(type="date") */
    private $started;

    /** @MongoDB\Field(type="date") */
    private $left;


    /** @MongoDB\ReferenceMany() */
    private $commands;
     /** @MongoDB\EmbedOne(targetDocument="Address") */
     private $address;

     /**
      * @MongoDB\EmbedMany(targetDocument="Role")
      */
     private $Role;

     /**
      * @return mixed
      */
     public function getRole()
     {
         return $this->Role;
     }

     /**
      * @param mixed $Role
      */
     public function setRole($Role): void
     {
         $this->Role = $Role;
     }


    public function  __construct() { $this->commands = new ArrayCollection(); }

    public function getCommands() { return $this->commands; }
    public function addCommands(Command $comm) { $this->commands[] = $comm; }



    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }


    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password): void
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * @param mixed $login
     */
    public function setLogin($login): void
    {
        $this->login = $login;
    }


    /**
     * @return mixed
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @param mixed $lastname
     */
    public function setLastname($lastname): void
    {
        $this->lastname = $lastname;
    }


    public function getId()
    {
        return $this->id;
    }

    public function getChanges()
    {
        return $this->changes;
    }

    public function incrementChanges()
    {
        $this->changes++;
    }


    public function getFirstname()
    {
        return $this->firstname;
    }

    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
    }

    public function getSalary()
    {
        return $this->salary;
    }

    public function setSalary($salary)
    {
        $this->salary = (int)$salary;
    }

    public function getStarted()
    {
        return $this->started;
    }

    public function setStarted(DateTime $started)
    {
        $this->started = $started;
    }

    public function getLeft()
    {
        return $this->left;
    }

    public function setLeft(DateTime $left)
    {
        $this->left = $left;
    }

    public function getAddress()
    {
        return $this->address;
    }

    public function setAddress(Address $address)
    {
        $this->address = $address;
    }

     /**
      * @param mixed $commands
      */
     public function setCommands($commands): void
     {
         $this->commands = $commands;
     }

     /**
      * @param mixed $id
      */
     public function setId($id): void
     {
         $this->id = $id;
     }

}
```
```

**Comment by Belssem** [comment]
``` <?php

namespace App\Document;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use DateTime;
use Doctrine\ORM\Mapping as ORM;


/**
 *
 * @ApiResource()
 * @MongoDB\Document(repositoryClass="App\Repository\UserRepository")
 *
 *
 *
 */
 class User
{
    /** @MongoDB\Id*/
    private $id;

    /** @MongoDB\Field(type="string") */
    private $firstname;

    /** @MongoDB\Field(type="string") */
    private $lastname;

    /** @MongoDB\Field(type="string") */
    private $email;

    /** @MongoDB\Field(type="string") */
    private $login;
    /** @MongoDB\Field(type="string") */
    private $password;
    /** @MongoDB\Field(type="int") */
    private $salary;

    /** @MongoDB\Field(type="date") */
    private $started;

    /** @MongoDB\Field(type="date") */
    private $left;


    /** @MongoDB\ReferenceMany() */
    private $commands;
     /** @MongoDB\EmbedOne(targetDocument="Address") */
     private $address;

     /**
      * @MongoDB\EmbedMany(targetDocument="Role")
      */
     private $Role;

     /**
      * @return mixed
      */
     public function getRole()
     {
         return $this->Role;
     }

     /**
      * @param mixed $Role
      */
     public function setRole($Role): void
     {
         $this->Role = $Role;
     }


    public function  __construct() { $this->commands = new ArrayCollection(); }

    public function getCommands() { return $this->commands; }
    public function addCommands(Command $comm) { $this->commands[] = $comm; }



    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail($email): void
    {
        $this->email = $email;
    }


    /**
     * @return mixed
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * @param mixed $password
     */
    public function setPassword($password): void
    {
        $this->password = $password;
    }

    /**
     * @return mixed
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * @param mixed $login
     */
    public function setLogin($login): void
    {
        $this->login = $login;
    }


    /**
     * @return mixed
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * @param mixed $lastname
     */
    public function setLastname($lastname): void
    {
        $this->lastname = $lastname;
    }


    public function getId()
    {
        return $this->id;
    }

    public function getChanges()
    {
        return $this->changes;
    }

    public function incrementChanges()
    {
        $this->changes++;
    }


    public function getFirstname()
    {
        return $this->firstname;
    }

    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
    }

    public function getSalary()
    {
        return $this->salary;
    }

    public function setSalary($salary)
    {
        $this->salary = (int)$salary;
    }

    public function getStarted()
    {
        return $this->started;
    }

    public function setStarted(DateTime $started)
    {
        $this->started = $started;
    }

    public function getLeft()
    {
        return $this->left;
    }

    public function setLeft(DateTime $left)
    {
        $this->left = $left;
    }

    public function getAddress()
    {
        return $this->address;
    }

    public function setAddress(Address $address)
    {
        $this->address = $address;
    }

     /**
      * @param mixed $commands
      */
     public function setCommands($commands): void
     {
         $this->commands = $commands;
     }

     /**
      * @param mixed $id
      */
     public function setId($id): void
     {
         $this->id = $id;
     }

}
==> this is the origin code of my repository but nothing happend . i got always the same problem

**Comment by Belssem** [comment]
Now i got a new error ```The repository for "App\Document\User" must be an instance of "Doctrine\ODM\MongoDB\Repository\DocumentRepository".
