### ISSUE TITLE
configuration of file Object to store in GridFs

### ISSUE THREAD

**Issue by OsvalGuiany** [doctrine/DoctrineMongoDBBundle#551]
Hello, 
   Please, I have followed this page: [doctrine-project-site](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/storing-files-with-mongogridfs.html#storing-files-with-gridfs) to map my File Object but when I run the command `php bin/console doctrine:mongodb:mapping:info`, I have the following error.
**Unknown property 'bucketName' on annotation 'Doctrine\ODM\MongoDB\Mapping\Annotations\File'.**
 I don't know why. Please there is somebody who can help me ?

**Comment by alcaeus** [comment]
You were looking at the documentation for 2.0, which version of this bundle and `doctrine/mongodb-odm` are you using?

**Comment by OsvalGuiany** [comment]
I'm using the `version 1.2.8 ` of `doctrine/mongodb-odm`.

**Comment by OsvalGuiany** [comment]
please is there the version of `doctrine/mongodb-odm-bundle ` which is using `doctrine/mongodb-odm version 2.0` ? I'm using `symfony 3.4`

**Comment by OsvalGuiany** [comment]
thank you for your answer.
