### ISSUE TITLE
Symfony 4.2 deprecation : Symfony\Component\HttpKernel\Kernel::getRootDir()

### ISSUE THREAD

**Issue by kpn13** [doctrine/DoctrineMongoDBBundle#552]
Hi, 

I suppose you already know but still`Symfony\Component\HttpKernel\Kernel::getRootDir()` method is deprecated since sf 4.2

https://github.com/doctrine/DoctrineMongoDBBundle/blob/a896fcf2f50ca8fa253f8d4608192bf50190d8bc/Command/LoadDataFixturesDoctrineODMCommand.php#L94

https://github.com/doctrine/DoctrineMongoDBBundle/blob/a896fcf2f50ca8fa253f8d4608192bf50190d8bc/Command/LoadDataFixturesDoctrineODMCommand.php#L101

**Comment by malarzm** [comment]
@kpn13 thanks for the tip! Would you be willing to work on a PR to get rid of said code?

**Comment by kpn13** [comment]
Ok I can try :)
