### ISSUE TITLE
php bin/console doctrine:mongodb:generate:documents 

### ISSUE THREAD

**Issue by mouad-mahfoud** [doctrine/DoctrineMongoDBBundle#560]
php bin/console doctrine:mongodb:generate:documents not work for symfony 4 each time he asks for a  bundel argumant

**Comment by malarzm** [comment]
We no longer support generating documents, please see https://github.com/doctrine/DoctrineMongoDBBundle/issues/479#issuecomment-426149593 for an explanation.
