### ISSUE TITLE
Symfony 4 profiler empty

### ISSUE THREAD

**Issue by markitosgv** [doctrine/DoctrineMongoDBBundle#563]
I have no queries on Symfony profiler when changing to 4.0.0-RC1

**Comment by malarzm** [comment]
@markitosgv you mean that there should be some queries logged, right?

**Comment by markitosgv** [comment]
Yes, I don't see any query. I don't know if I've got something wrong configurated

**Comment by markitosgv** [comment]
I see that in $this->commandLogger in CommandDataCollector there's no data

**Comment by alcaeus** [comment]
Cross-referencing with https://github.com/doctrine/mongodb-odm/issues/2037, but still need to investigate whether the issue is in the logger itself or the registration in this bundle.
