### ISSUE TITLE
ReplaceRoot not working with Doctrine

### ISSUE THREAD

**Issue by aspire-shatheesh** [doctrine/DoctrineMongoDBBundle#565]
I am trying to achieve replaceRoot in doctrine. Seems there is some issue or am not sure if I am missing something.

```
[ 
{ "$unwind": "$data" }, 
{ "$match": { "$and": [ { "key": "885_2018_" } ] } }, 
{ "$group": { "_id": "null", "ranked": { "$push": "$data"  } } },
{ "$unwind": { "path": "$ranked", "includeArrayIndex": "rank" } },
{ "$addFields": {"ranked.rank": { $add: [ "$rank", 1] }} },
{ "$replaceRoot": { "newRoot": "$ranked" }  }
]);
```

I am trying to do the above mongo aggregation stage in Doctrine. Could you please help if this is a bug in  Mongo ODM.
```
$builder = $this->createAggregationBuilder();
$groupByStage = $builder->group()->field('_id')->expression('null');
$groupByStage->field('ranked')->push('$data');
$groupByStage->unwind('$ranked')->includeArrayIndex('rank');
$builder->replaceRoot('$ranked');
```

I am getting the below error
`
'expected an object as specification for $replaceRoot stage, got string', 'stackTrace' => '#0 /api-r3/vendor/mongodb/mongodb/src/Operation/DatabaseCommand.php(94)`

**Comment by alcaeus** [comment]
Yikes - that's not good. For ODM 1.x, this is fixed by https://github.com/doctrine/mongodb/pull/333 as the error is actually in the `doctrine/mongodb` library. For 2.0, the fix will be ported to ODM directly. I'm closing this issue as it's being fixed in the respective libraries. Thanks for reporting it!

**Comment by aspire-shatheesh** [comment]
Thanks much @alcaeus 

For now until [#333](https://github.com/doctrine/mongodb/pull/333) is merged,  I did a workaround by passing an expression . 
```

$expr = $builder->expr();
$expr->field('newRoot')->expression('$ranked');
$builder->replaceRoot($expr);
```

**Comment by alcaeus** [comment]
1.6.4 has been released, containing a fix 👍
