### ISSUE TITLE
Symfony 2.8 and MongoDB 4 compatible version

### ISSUE THREAD

**Issue by cithukyaw** [doctrine/DoctrineMongoDBBundle#573]
Which version is suitable for Symfony 2.8 and MongoDB 4?

**Comment by malarzm** [comment]
Take the highest one `composer` will allow due to Symfony constraints

**Comment by cithukyaw** [comment]
This is the highest one I could install for Symfony 2.8.14, PHP 7.1 and MongoDB 4

     "doctrine/mongodb-odm-bundle": "~3.4"

**Comment by xabbuh** [comment]
3.5.0 was the first release that dropped support for Symfony < 3.4. So this looks expected to me.

**Comment by malarzm** [comment]
@cithukyaw please note that MongoDB server versions are not constrained in any way, underlying ODM will work with any version of MongoDB. You could just be missing some features of the bundle/library due to usage of older versions.

**Comment by alcaeus** [comment]
Running `composer why-not doctrine/mongodb-odm-bundle 3.5` will tell you what constraints forbid it from updating to that bundle version. That said, even with the 3.4 release of the bundle you'll be able to install any 1.x version of mongodb-odm, as long as all platform constraints are satisfied. With respect to the old Symfony version, ODM 1.x only has one direct dependency on `symfony/console` and allows 2.3 and newer there, so installing a new ODM version shouldn't be a problem. You can confirm this by running `composer show doctrine/mongodb-odm`.

Also, as @malarzm already said, all MongoDB 1.x versions work with MongoDB 4. You may have to work around a deprecation here or there (e.g. if you are running aggregation pipelines without the `cursor` option), but other than that there aren't any issues.
