### ISSUE TITLE
YamlDriver parameter is missing

### ISSUE THREAD

**Issue by 0mars** [doctrine/DoctrineMongoDBBundle#574]
Trying to use the bundle with yaml mappings, found the XML driver definition in the bundle but not the Yaml one

The service "doctrine_mongodb.odm.default_yml_metadata_driver" has a dependency on a non-existent parameter "doctrine_mongodb.odm.metadata.yml.class".

**Comment by malarzm** [comment]
@0mars which version of bundle are you trying to use? Yaml driver is gone in 4.x

**Comment by alcaeus** [comment]
The error message is correct: since we're dropping the YAML metadata driver in 4.0, the parameter is no longer there. However, the service ID you mentioned is not from the bundle and doesn't appear in the source code. Did you maybe try to create your own metadata driver for YAML?

**Comment by 0mars** [comment]
you can close this issue, I should have documnted the steps, but now don't have time to do so.

Thanks anyway

**Comment by 0mars** [comment]
ah yes, that was when I set the driver mapping to yml, it should throw unsupported driver exception maybe

**Comment by malarzm** [comment]
We could make [`type` an enum instead of a scalar node](https://github.com/doctrine/DoctrineMongoDBBundle/blob/b6ceeda9eafcbcb7be4fd753f499a7303981b0e6/DependencyInjection/Configuration.php#L227) to let Symfony throw an exception for us.

**Comment by alcaeus** [comment]
> We could make [`type` an enum instead of a scalar node](https://github.com/doctrine/DoctrineMongoDBBundle/blob/b6ceeda9eafcbcb7be4fd753f499a7303981b0e6/DependencyInjection/Configuration.php#L227) to let Symfony throw an exception for us.

That's a good idea 👍

**Comment by Sander-Toonen** [comment]
Just in case someone stumbles upon this. I created a console command that helped me converting my mappings from Yaml to XML. It is not complete (just completed the job for me for about 90%). Unfortunately I do not have the time to spend more time on it but maybe it can be to any help for anyone.

You will need to change the paths for your own needs.
https://gist.github.com/Sander-Toonen/25860bb358eb8f2e7f51f3fe1512cbb5

**Comment by malarzm** [comment]
FWIW ODM is providing a command doing exactly that in 1.3 :) https://github.com/doctrine/mongodb-odm/blob/1.3.x/lib/Doctrine/ODM/MongoDB/Tools/Console/Command/ConvertMappingToXmlCommand.php

**Comment by Sander-Toonen** [comment]
FML...
