### ISSUE TITLE
bug with mismatch type of method in 4.0.0-RC2

### ISSUE THREAD

**Issue by lljaworski** [doctrine/DoctrineMongoDBBundle#584]
After clear cache in Symfony, I'd error:
`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Doctrine\Bundle\MongoDBBundle\APM\CommandLoggerRegistry::addLogger() must implement interface Doctrine\ODM\MongoDB\APM\CommandLoggerInterface, instance of Doctrine\Bundle\MongoDBBundle\APM\PSRCommandLogger given, called in /srv/api/vendor/doctrine/mongodb-odm-bundle/APM/CommandLoggerRegistry.php on line 18 in /srv/api/vendor/doctrine/mongodb-odm-bundle/APM/CommandLoggerRegistry.php on line 36
`

**Comment by alcaeus** [comment]
I’m travelling today, but I’ll take a look later during the day. I may have forgot to update something before merging #569, so I’ll most likely fix this in a third RC quickly.
