### ISSUE TITLE
Remove PHP 7.4 from `allow_failures`

### ISSUE THREAD

**Issue by carusogabriel** [doctrine/DoctrineMongoDBBundle#587]
PHP 7.4 will be released [soon](https://wiki.php.net/todo/php74) and we need to ensure that `Doctrine` is compatible with it.

All we need to do is to remove these following lines

https://github.com/doctrine/DoctrineMongoDBBundle/blob/227d908c5d8142fe4bc5c709f925ebacf78c6a4c/.travis.yml#L16-L17

 and verify that everything is working.

This is a very good issue for those who want to participate in https://hacktoberfest.digitalocean.com.

**Comment by alcaeus** [comment]
Fixed in #588.
