### ISSUE TITLE
Query logs on profiler

### ISSUE THREAD

**Issue by markitosgv** [doctrine/DoctrineMongoDBBundle#591]
Hi!

In new 4.0 version now query logs are like this:

```
{"aggregate":"Posts","pipeline":[{"$match":{"posts.enabled":true,"posts.category":{"$oid":"xxxxx"}}},{"$lookup":{"from":"categories","localField":"category","foreignField":"_id","as":"category"}},{"$unwind":"$category"}],"allowDiskUse":false,"cursor":{},"$db":"database","$readPreference":{"mode":"primaryPreferred"},"lsid":{"id":{"$binary":"wpUeqMtATWqnpmB7afgqzA==","$type":"04"}}}

```
Old way was like this:

```
db.Posts.aggregate([ { "$match": [ ] }, { "$lookup": { "from": "PostCategories", "localField": "profile", "foreignField": "_id", "as": "category" } }, { "$unwind": "$category" }, { "$addFields": { "categoryName": "$category.name" } }, { "$match": { "owner": ObjectId("xxxx") } }, { "$sort": { "createdAt": -1 } }, { "$skip": 0 }, { "$limit": 10 } ], { "cursor": true });
```

I find more usable old way because you could copy queries and execute it without any transformation.

Is it possible to show queries in a pretty way?

**Comment by alcaeus** [comment]
We no longer log queries, but rather log the commands as they are sent to the server. What we shod is a command document that can be passed to `db.runCommand()` in your shell. Converting these command documents to calls of the `mongo` shell methods is a large amount of work that isn't worth it IMO as you can just use `runCommand` to run the command in question.
