### ISSUE TITLE
Symfony 4.4 deprecation / Symfony 5.0 compatibility

### ISSUE THREAD

**Issue by teohhanhui** [doctrine/DoctrineMongoDBBundle#596]
> Not declaring the "Symfony\Bridge\Doctrine\DependencyInjection\AbstractDoctrineExtension::getMetadataDriverClass" method in class "Doctrine\Bundle\MongoDBBundle\DependencyInjection\DoctrineMongoDBExtension" is deprecated since Symfony 4.4. This method will be abstract in Symfony 5.0.

Spotted in https://github.com/api-platform/core/pull/3009

**Comment by alcaeus** [comment]
Thanks. I’m wrapping up Symfony compatibility for all the bundles currently. We’ll release a 5.0 release of the bundle in time for Symfony 5.

If you’d like to send a pull request, please go ahead!
