### ISSUE TITLE
PrettyDataCollector generates a notice in php7.4

### ISSUE THREAD

**Issue by Nadrshin** [doctrine/DoctrineMongoDBBundle#607]
Version `3.6.1`

[PrettyDataCollector](https://github.com/doctrine/DoctrineMongoDBBundle/blob/3.6.1/DataCollector/PrettyDataCollector.php) generates a notice `Trying to access array offset on value of type int` in lline [105](https://github.com/doctrine/DoctrineMongoDBBundle/blob/3.6.1/DataCollector/PrettyDataCollector.php#L105).

This notice type was added in php7.4 https://www.php.net/manual/en/migration74.incompatible.php#migration74.incompatible.core.non-array-access

**Comment by malarzm** [comment]
Closing as #608 was merged
