### ISSUE TITLE
Is there no DocumentUserProvider?

### ISSUE THREAD

**Issue by cnizzardini** [doctrine/DoctrineMongoDBBundle#609]
Does this bundle have anything akin to the EntityUserProvider, except for Documents obviously. So something that implements UserProviderInterface for usage with Symfony.

**Comment by alcaeus** [comment]
No, there is no such class. This could be added based on the EntityUserProvider class provided in the Symfony DoctrineBridge. Want to give it a shot?

**Comment by cnizzardini** [comment]
This in particular was related to an issue I was having getting oAuth working here: https://github.com/trikoder/oauth2-bundle/issues/103 and I was able to work around it.
