### ISSUE TITLE
Incompatibility with Symfony 4.3.10+

### ISSUE THREAD

**Issue by excentrik** [doctrine/DoctrineMongoDBBundle#616]
Hello

In our company's project we are currently using Symfony 4.4 branch, but we are still behind in our move towards using Doctrine ODM 2.

Therefore we still rely on doctrine/mongodb-odm-bundle for the interface beween Symfony and doctrine odm 1.3.

Unfortunately, the PR https://github.com/symfony/symfony/pull/34955 has broken interface compatibility between the doctrine/mongodb-odm-bundle and Symfony's latest versions (4.4.2+,4.3.10+,5.0.2+):

```
PHP Fatal error:  Declaration of Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType::getLoader(Doctrine\Common\Persistence\ObjectManager $manager, $queryBuilder, $class) 
must be compatible with Symfony\Bridge\Doctrine\Form\Type\DoctrineType::getLoader(Doctrine\Persistence\ObjectManager $manager, $queryBuilder, $class)
```

Since the interface is almost the same, I think the fix should be just changing the method `Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType::getLoader` to receive a `Doctrine\Persistence\ObjectManager` but I'm not sure if this would cause any other incompatibilities.

**Comment by greg0ire** [comment]
Hi! Thanks for reporting this. The issue is not with this bundle though, it is with Symfony (more exactly, the `DoctrineType` class). I'm going to work on a PR rightaway, and link to this issue in it, you should see the PR link pop here when I am done.

**Comment by excentrik** [comment]
@greg0ire Thank you for the swift reply and fixes. Hopefully symfony 4.4.5 is released soon :smile:
