### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by runtothefather** [doctrine/DoctrineMongoDBBundle#640]
current doctrine/mongodb-odm dependency is a bit outdated (doctrine/mongodb-odm: ^2.0.0), is it possible to upgrade it to the newest version - ^2.1, since some features (ex. DateImmutableType) missed?

**Comment by malarzm** [comment]
`^2.0.0` constraint is allowing `2.1.0` version to be installed, what's the problem?

**Comment by runtothefather** [comment]
🤦 ignore me, figured this case out, close the issue
