### ISSUE TITLE
config/packages/prod/doctrine_mongodb.yaml expects not existing service

### ISSUE THREAD

**Issue by es-cologne** [doctrine/DoctrineMongoDBBundle#680]
My environment:
- PhpStorm 2021.1.4 with Symfony Support Plugin 0.23.210
- Symfony 4.4.16
- doctrine/mongodb-odm 2.0.6
- doctrine/mongodb-odm-bundle 4.3.0

<img width="573" alt="screenshot" src="https://user-images.githubusercontent.com/76219066/125196196-368b5600-e259-11eb-9e52-7827603d470b.png">

**Comment by malarzm** [comment]
This again comes from the flex recipe and needs to be fixed there (https://github.com/symfony/recipes-contrib/blob/master/doctrine/mongodb-odm-bundle/3.3/config/packages/prod/doctrine_mongodb.yaml), not in the bundle itself.
