### ISSUE TITLE
Remove usage of the whole container

### ISSUE THREAD

**Issue by franmomu** [doctrine/DoctrineMongoDBBundle#688]
Right now [`CacheWarmers`](https://github.com/doctrine/DoctrineMongoDBBundle/tree/4.4.x/CacheWarmer) receive the whole container and also in Command:

https://github.com/doctrine/DoctrineMongoDBBundle/blob/ccc51c0c09e35a6e613e17a0bfa87a3c52f8e397/Command/DoctrineODMCommand.php#L29-L31

it would be nice to inject only the used services and parameters and remove the usage of the whole container.

**Comment by IonBazan** [comment]
This should be aiming v5.0 because commands are marked as `@internal` since then and container-related methods are marked for removal in v5:
https://github.com/doctrine/DoctrineMongoDBBundle/blob/6f1b0dad14615ad4041ff40382126901f1841f9f/Command/DoctrineODMCommand.php#L46-L59
