### ISSUE TITLE
Usage of setMetadataCacheImpl raises deprecation warning

### ISSUE THREAD

**Issue by calinblaga** [doctrine/DoctrineMongoDBBundle#696]
The usage of [setMetadataCacheImpl](https://github.com/doctrine/DoctrineMongoDBBundle/blob/4.4.x/DependencyInjection/DoctrineMongoDBExtension.php#L208) raises deprecation in doctrine/mongodb-odm from 2.2.
https://github.com/doctrine/mongodb-odm/blob/2.3.x/lib/Doctrine/ODM/MongoDB/Configuration.php#L210

**Comment by malarzm** [comment]
This will be fixed once #675 is done
