### ISSUE TITLE
Add version numbers to the installation instructions

### ISSUE THREAD

**Issue by blogsh** [doctrine/DoctrineMongoDBBundle#72]
If you try to install the DoctrineMongoDBBundle as it is described in the [documentation] [1] it won't work. The problem is that the given deps file doesn't define a certain version of the bundle and obviously there is a BC break with the master branch, because "AbstractDoctrineExtension" cannot be found.

So I think it would be a good idea to add a 

    version=v2.0.1

to the deps file snippet for Symfony v.2.0.8 and maybe start to maintain a list of compatible Symfony/DoctrineMongoDBBundle versions? Another possibility would be to give a list of recommended versions for all the bundles in the Symfony documentation for the certain Symfony versions and just give an explanation on how to use a certain version of the bundle here.

[1]: https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Resources/doc/index.rst

**Comment by malarzm** [comment]
Closing the issue since Symfony 2.0 and deps  are no longer a thing :)
