### ISSUE TITLE
[doc] Unrecognized option "metadata_cache_driver" under "doctrine_mongodb". 

### ISSUE THREAD

**Issue by sormes** [doctrine/DoctrineMongoDBBundle#722]
Version:

4.4.1

https://github.com/doctrine/DoctrineMongoDBBundle/blob/4.4.x/Resources/doc/config.rst

In "Multiple Connections" uses option _metadata_cache_driver_ under _doctrine_mongodb_ but it is not supported,

[PR #721](https://github.com/doctrine/DoctrineMongoDBBundle/pull/721)

**Comment by malarzm** [comment]
I've copied the text to #721
