### ISSUE TITLE
Can you add SCRAM-SHA-256 support?

### ISSUE THREAD

**Issue by Neustradamus** [doctrine/DoctrineMongoDBBundle#727]
Dear @doctrine team,

I wish you a Happy New Year 2022!

Can you add SCRAM-SHA-256 support?

Thanks in advance.

Linked to:
- https://github.com/scram-xmpp/info/issues/1

**Comment by malarzm** [comment]
@Neustradamus happy new year to you too! 🎉

> Can you add SCRAM-SHA-256 support?

I assume you'd like to see new `authMechanism` added? If yes it's pretty straightforward to do so, you can check where [SCRAM-SHA-1 is used](https://github.com/doctrine/DoctrineMongoDBBundle/search?q=SCRAM-SHA-1) and mimic it :)

**Comment by Neustradamus** [comment]
@malarzm: Yes it is ^^

**Comment by franmomu** [comment]
It was solved in https://github.com/doctrine/DoctrineMongoDBBundle/pull/728

**Comment by Neustradamus** [comment]
@franmomu: Thanks a lot! :)

Little question, the list has not an order, from the best to the worst?

**Comment by malarzm** [comment]
> Little question, the list has not an order, from the best to the worst?

No the order is pretty random as far as I know
