### ISSUE TITLE
Attribute reader is missing

### ISSUE THREAD

**Issue by smilesrg** [doctrine/DoctrineMongoDBBundle#730]
In order to use Doctrine Mongodb attributes, attributes metadata reader needs to be implemented

**Comment by malarzm** [comment]
Attributes were implemented in https://github.com/doctrine/DoctrineMongoDBBundle/pull/692 and are released, what seems to be missing?

**Comment by smilesrg** [comment]
Port to 4.3.1 ?

**Comment by IonBazan** [comment]
@smilesrg I don't think there were any major breaking changes between 4.3 and 4.4. Is there anything that blocks you from upgrading to 4.4 branch?

**Comment by malarzm** [comment]
@smilesrg attribute reader was a feature and as such lands in a minor release, not a bugfix one. Please upgrade to latest version to use latest features.

**Comment by smilesrg** [comment]
@IonBazan @malarzm I probably needed to say `4.3`, but if it's supposed to be since `4.4` please update the docs, docs say that `4.4` is an upcoming release and not released yet

>Is there anything that blocks you from upgrading to 4.4 branch?

Actually, I've just looked at the docs & source, I'm not using the bundle right now

**Comment by malarzm** [comment]
I'll reach out to Symfony folks, AFAIR the change needs to be done on their end :+1:
