### ISSUE TITLE
is Symfony 6 and php 8 is supported 

### ISSUE THREAD

**Issue by edeebee** [doctrine/DoctrineMongoDBBundle#733]
I'm getting this error during install

 - doctrine/mongodb-odm-bundle[4.3.0, ..., 4.3.1] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - doctrine/mongodb-odm-bundle[4.4.0, ..., 4.4.2] require ext-mongodb ^1.5 -> it is missing from your system. Install or enable PHP's mongodb extension.
    - Root composer.json requires doctrine/mongodb-odm-bundle ^4.3 -> satisfiable by doctrine/mongodb-odm-bundle[4.3.0, ..., 4.4.2].

Is SF6 and PHP 8 is still unsupported ?

**Comment by malarzm** [comment]
Everything you mention is supported as per our [composer.json](https://github.com/doctrine/DoctrineMongoDBBundle/blob/4.5.x/composer.json).

I'd focus on this part of the error:

> require ext-mongodb ^1.5 -> it is missing from your system. Install or enable PHP's mongodb extension.
