### ISSUE TITLE
UniqueEntity::$service is considered final

### ISSUE THREAD

**Issue by IonBazan** [doctrine/DoctrineMongoDBBundle#741]
Running a test suite in a Symfony 6.1 application throws a deprecation notice:
```
The "Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity::$service" property is considered final. You should not override it in "Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique".
```

This is because `Doctrine\Bundle\MongoDBBundle\Validator\Constraints\Unique` class overrides `$service` property with a different default value.

Another way to override it would be to copy the constructor parameters and set the default value there.

https://github.com/doctrine/DoctrineMongoDBBundle/blob/4.6.x/Validator/Constraints/Unique.php

**Comment by franmomu** [comment]
Fixed in https://github.com/doctrine/DoctrineMongoDBBundle/pull/777
