### ISSUE TITLE
Feature request: Implement a DocumentType or MongoDocumentType Field à la EntityType field

### ISSUE THREAD

**Issue by landure** [doctrine/DoctrineMongoDBBundle#749]
Symfony provides a simple way to create select fields from database tables using the [EntityType field](https://symfony.com/doc/current/reference/forms/types/entity.html).

Unfortunately, as far as I was able to find, Doctrine ODM does not provide an equivalent field for MongoDB (or couchDB). Thus this feature request:

Please create a (simplified) DocumentType field that allow to fetch its data from a MongoDB (or CouchDB) Document.

Thank you for your work.

**Comment by IonBazan** [comment]
There is already a `DocumentType` form type: https://www.doctrine-project.org/projects/doctrine-mongodb-bundle/en/current/form_validation.html#documenttype

**Comment by landure** [comment]
Ok thank you, my bad.
