### ISSUE TITLE
Custom Types

### ISSUE THREAD

**Issue by henrikbjorn** [doctrine/DoctrineMongoDBBundle#75]
I had an idea to create a better flow for handing uploaded files in Symfony2 through a custom type that would mape the file from File to a string and then back again. Unfortunately there is no place to add a custom type like in DoctrineBundle.

Theese are some of the things i have tried.
1. In a bundles build method. This is unfortunately only ran when the Container is build.
2. in a bundles boot method but that is too late because of Doctrine Bundle being enabled before my custom one.

Any further ideas without implementing this directly would be good ;)

**Comment by hairmare** [comment]
Has this been resolved yet?

I was about to dive in and write a compilerpass that finds tagged custom types and then applies them like described on [this blog](http://php-and-symfony.matthiasnoback.nl/2012/09/symfony2-mongodb-odm-creating-custom-types-with-dependencies/).

Would that be a way to do this and would you want me to upstream it ilke that?

**Comment by dadeky** [comment]
Does anyone know when will this issue be resolved?

**Comment by alcaeus** [comment]
I've scheduled this for an upcoming 3.3.0 release, but I can't give you a timeline as to when it will happen.

**Comment by TheHett** [comment]
it would be very convenient to be able to configure custom data types like in the dbal
https://symfony.com/doc/current/doctrine/dbal.html
```
doctrine:
    dbal:
        types:
            custom_first:  App\Type\CustomFirst
            custom_second: App\Type\CustomSecond
```

**Comment by juliusstoerrle** [comment]
bump :) would like to see this coming. Where are you currently registering your types?

**Comment by juliusstoerrle** [comment]
for now I added following to my Kernel::boot() method. Not sure if it's the best place to register types?

`  public function boot()
    {
        parent::boot();
        try {
            $types = $this->getContainer()->getParameter('odm.types');
            foreach ($types as $key => $fqcn) {
                Type::addType($key, $fqcn);
            }
        } catch (\InvalidArgumentException $e) {
            // do nothing if parameter not defined
        }
    }
`

**Comment by juliusstoerrle** [comment]
I would propose adding above code to the boot() method of [DoctrineMongoDBBundle.php](https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/DoctrineMongoDBBundle.php)
With the types listed under the config key "doctrine_mongodb.types".

@alcaeus would that solution suit you? I could prepare a PR.

**Comment by alcaeus** [comment]
Yes, a PR would be a good starting point 👍

**Comment by alexmorbo** [comment]
Bump. Any news?

**Comment by alcaeus** [comment]
See related PR (#520): it needs tests and looks like the original author is no longer working on it. If you need this, consider picking up the PR.

**Comment by juliusstoerrle** [comment]
Yes, I'm unfortunantly not able to to put any time towards this PR right now. Adding [this](https://github.com/doctrine/DoctrineMongoDBBundle/issues/75#issuecomment-451662294) code to my own Kernel works very well for the time beeing. All information about the current state are in the PR, it shouldn't be hard to pick up. If there were a lot of changes to the type registration or Bundle in the meantime (I don't know where all the time went since I worked on that...) it might even be worth to apply the changes to the current master version.

**Comment by alcaeus** [comment]
Added in #631.
