### ISSUE TITLE
Fix symfony 6.4/7.0 deprecations

### ISSUE THREAD

**Issue by Nyoob** [doctrine/DoctrineMongoDBBundle#809]
Is there already a plan when symfony 7 will be supported?

`User Deprecated: The "Doctrine\Bundle\MongoDBBundle\CacheWarmer\PersistentCollectionCacheWarmer::warmUp()" method will require a new "string|null $buildDir" argument in the next major version of its interface "Symfony\Component\HttpKernel\CacheWarmer\WarmableInterface", not defining it is deprecated.`

`User Deprecated: The "Doctrine\Bundle\MongoDBBundle\CacheWarmer\ProxyCacheWarmer::warmUp()" method will require a new "string|null $buildDir" argument in the next major version of its interface "Symfony\Component\HttpKernel\CacheWarmer\WarmableInterface", not defining it is deprecated.`

`User Deprecated: The "Doctrine\Bundle\MongoDBBundle\CacheWarmer\HydratorCacheWarmer::warmUp()" method will require a new "string|null $buildDir" argument in the next major version of its interface "Symfony\Component\HttpKernel\CacheWarmer\WarmableInterface", not defining it is deprecated.`

**Comment by GromNaN** [comment]
We are actively working on a new major version 5.0 that will support Symfony 6.4 and 7.0

The deprecation have been fixed in  https://github.com/doctrine/DoctrineMongoDBBundle/pull/789

**Comment by lchhieu** [comment]
Still haven't support symfony 7 yet ?

**Comment by malarzm** [comment]
@lchhieu Symfony 7 support is part of the 5.0 release like @GromNaN mentioned, you can track its progress here https://github.com/doctrine/DoctrineMongoDBBundle/milestone/34. Please try helping out instead of posting such questions
