### ISSUE TITLE
Find deprecated code

### ISSUE THREAD

**Issue by malarzm** [doctrine/DoctrineMongoDBBundle#813]
While reviewing native types I've found this

https://github.com/doctrine/DoctrineMongoDBBundle/blob/6030b58119d4fe4b884a7c4ce3ba48c093baa8e5/DependencyInjection/DoctrineMongoDBExtension.php#L260-L265

Let's review any and all outstanding deprecations from 4.x

**Comment by GromNaN** [comment]
I think all deprecated code have been removed by:
- https://github.com/doctrine/DoctrineMongoDBBundle/pull/821
- https://github.com/doctrine/DoctrineMongoDBBundle/pull/819
- https://github.com/doctrine/DoctrineMongoDBBundle/pull/808
- https://github.com/doctrine/DoctrineMongoDBBundle/pull/804
- https://github.com/doctrine/DoctrineMongoDBBundle/pull/799
- https://github.com/doctrine/DoctrineMongoDBBundle/pull/795

**Comment by malarzm** [comment]
Cool, let's close then. Thanks! :tada:
