### ISSUE TITLE
Deprecated EventSubscriberInterface, use AsDoctrineListener

### ISSUE THREAD

**Issue by markitosgv** [doctrine/DoctrineMongoDBBundle#816]
Since symfony/doctrine-bridge 6.3: Registering "xxxxSubscriber" as a Doctrine subscriber is deprecated. Register it as a listener instead, using e.g. the #[AsDoctrineListener] attribute.

Is there any update for this?

**Comment by GromNaN** [comment]
Thanks for pointing this feature. It was introduced by https://github.com/doctrine/DoctrineBundle/pull/1561, renamed in https://github.com/doctrine/DoctrineBundle/pull/1592 and the `EventSubscriberInterface` was deprecated in https://github.com/doctrine/DoctrineBundle/pull/1664.

I'll work on it.

**Comment by GromNaN** [comment]
@markitosgv You can use `#[AsDocumentListener]` from the `DoctrineMongoDBBundle`.

I opened a PR to deprecate the `EventSubscriberInterface`, so we can remove it in 5.0.

**Comment by GromNaN** [comment]
The deprecation message comes from [`symfony/doctrine-bridge`](https://github.com/symfony/doctrine-bridge/blob/bd181daf2851821c3aef20b779d37002cfd2e833/ContainerAwareEventManager.php#L211-L212).  The name of the referenced attribute should be removed or depend on if ORM or ODM are used.

**Comment by GromNaN** [comment]
I opened a PR on symfony bridge to update the deprecation message https://github.com/symfony/symfony/pull/53184 and update the doc to show usage of the new attribute #817
