### ISSUE TITLE
Non-existent service after fresh installation on branch 5.0.x

### ISSUE THREAD

**Issue by michaelthieulin** [doctrine/DoctrineMongoDBBundle#830]
Environment : 
* Symfony 7.0
* PHP 8.3 with mongodb extension

When I install a fresh version of Symfony with the symfony cli :

`symfony new test --webapp --version="stable"`

Then, i add the DoctrineMongoDBBundle :

`composer require doctrine/mongodb-odm-bundle:5.0.x-dev`

Then I answer yes for the recipe execution.

I have the following error while the execution of the @auto-scripts part of composer.json, more precisely in the cache:clear command :

`The service "doctrine_mongodb.odm.command.load_data_fixtures" has a dependency on a non-existent service "doctrine_mongodb.odm.symfony.fixtures.loader".`

I managed to fix this by installing doctrine/data-fixtures but I don't want to have this package in prod environment.

After accessing the page http://127.0.0.1:8000/ after launching `symfony serve` in the test directory, I have the following error :

`The profiler template "@DoctrineMongoDB/Collector/mongodb.html.twig" for data collector "mongodb" does not exist.`

Thanks and mainly thanks for the hard work.

**Comment by GromNaN** [comment]
I'm on it. Thanks for the report.

**Comment by MatTheCat** [comment]
Just hit this one; `$container->removeDefinition(LoadDataFixturesDoctrineODMCommand::class);` should be `$container->removeDefinition('doctrine_mongodb.odm.command.load_data_fixtures');` in the  `DoctrineMongoDBExtension`.

**Comment by franmomu** [comment]
That was my fault in https://github.com/doctrine/DoctrineMongoDBBundle/pull/810 that I added ids [based on the best practices](https://symfony.com/doc/current/bundles/best_practices.html#services), but forgot to search usages.

**Comment by MatTheCat** [comment]
@michaelthieulin maybe you should create another issue regarding the profiler template?

**Comment by michaelthieulin** [comment]
Thanks for the ultra speed fix 🤣
I open another issue for the template.

**Comment by GromNaN** [comment]
I'm looking at the template issue.

**Comment by GromNaN** [comment]
Template issue fix: https://github.com/doctrine/DoctrineMongoDBBundle/pull/833
