### ISSUE TITLE
AsDocumentListener attribute listeners are not called for fixtures

### ISSUE THREAD

**Issue by Addvilz** [doctrine/DoctrineMongoDBBundle#839]
Seems like `AsDocumentListener` marked listeners are not called during fixture load, with the same configuration working perfectly fine for all lifecycle events when interacting with DM, e.g. not during fixture load.

**Comment by malarzm** [comment]
@Addvilz thanks for the report! Would you be able to provide us a PR with a failing test?

**Comment by Addvilz** [comment]
Solved, the root cause was the interface between the keyboard and the chair. Nothing to do here.
