### ISSUE TITLE
Documentation link in README is broken

### ISSUE THREAD

**Issue by ariddlestone** [doctrine/DoctrineMongoDBBundle#840]
Following the documentation link in README.markdown results in a series of redirects, finally landing at a 404 page on Doctrine's docs site:

* http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html
* https://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html
* https://symfony.com/bundles/DoctrineMongoDBBundle/current/index.html
* https://www.doctrine-project.org/projects/doctrine-mongodb-bundle/en/current/index.html

**Comment by malarzm** [comment]
Thanks for letting us know! I need to figure out why `current` or `latest` is not working for docs. For anybody who stumbles here in the meantime please use this link: https://www.doctrine-project.org/projects/doctrine-mongodb-bundle/en/5.0/index.html

**Comment by malarzm** [comment]
The links have fixed themselves after #842. We forgot updating that file for quite a long time 👼
