### ISSUE TITLE
Functions fromPHP() and toCanonicalExtendedJSON() is deprecated

### ISSUE THREAD

**Issue by andrey-tech** [doctrine/DoctrineMongoDBBundle#855]
### DoctrineMongoDBBundle version(s) affected

**4.7.0**, up to 5.1.x

### Description

On PHP version **8.3.12**, `ext-mongodb` version **1.20.0** and `DoctrineMongoDBBundle` version **4.7.0**  I got two deprecation messages:

`Deprecated:  Function MongoDB\BSON\fromPHP() is deprecated in vendor/doctrine/mongodb-odm-bundle/DataCollector/CommandDataCollector.php on line 39.` 

`Deprecated:  Function MongoDB\BSON\toCanonicalExtendedJSON() is deprecated in vendor/doctrine/mongodb-odm-bundle/DataCollector/CommandDataCollector.php on line 39.`

I can't upgrade PHP version on my project from 8.2.24 to 8.3.12 with these two deprecation messages.  
Please, check and fix! I will create a pull request soon.

### Possible Solution

1) Change method `collect()` of class `\Doctrine\Bundle\MongoDBBundle\DataCollector\CommandDataCollector`

from:

```php
34                static function (Command $command): array {
35                    $dbProperty = '$db';
36
37                    return [
38                        'database' => $command->getCommand()->$dbProperty ?? '',
39                        'command' => json_decode(toCanonicalExtendedJSON(fromPHP($command->getCommand()))),
40                        'durationMicros' => $command->getDurationMicros(),
41                    ];
42               },
```

to:

```php
34                static function (Command $command): array {
35                    $dbProperty = '$db';
36                    $document = Document::fromPHP($command->getCommand());
37
38                    return [
39                        'database' => $command->getCommand()->$dbProperty ?? '',
40                        'command' => json_decode($document->toCanonicalExtendedJSON()),
41                        'durationMicros' => $command->getDurationMicros(),
42                    ];
43                },
```

2) Update version of `ext-mongodb` in `composer.json` to [^1.16](https://github.com/mongodb/mongo-php-driver/blob/v1.16/src/BSON/Document.stub.php):

```
"ext-mongodb": "^1.16"
```

**Comment by alcaeus** [comment]
> I can't upgrade PHP version on my project from 8.2.24 to 8.3.12 with these two deprecation messages.

These deprecations will only become a problem when we release version 2.0 of the extension - until then this is very much a configuration problem on your end. Deprecations are there to indicate that things will change in a future major version, not to block version updates before then.

**Comment by malarzm** [comment]
Closing as #856 was merged
