### ISSUE TITLE
Enable configuration of useTransactionalFlush in config

### ISSUE THREAD

**Issue by pkowalski700lm** [doctrine/DoctrineMongoDBBundle#860]
#### What

I would like to be able to pass useTransactionalFlush optionb via doctrine_mongodb.yml

#### Why

This feature is available in core doctrine mongodb configuration class https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/2.9/reference/transactions-and-concurrency.html

#### How

![image](https://github.com/user-attachments/assets/51f4767c-a9f4-4010-b845-65a55c1bc221)

**Comment by alcaeus** [comment]
This was added in #814, but never released. I released version 5.1.0, which adds support for the configuration option.
