### ISSUE TITLE
Critical error: LoadDataFixturesDoctrineODMCommand::setLogger(): Argument "$logger" must be of type Psr\Log\LoggerInterface, Closure given

### ISSUE THREAD

**Issue by sebastianstucke87** [doctrine/DoctrineMongoDBBundle#864]
### Bug Report

|    Q                                        |   A
|-------------------------------------------- | ------
| Version                                     | 5.1.0
| Previous Version if the bug is a regression | n/a

#### Summary

Critical error: `LoadDataFixturesDoctrineODMCommand::setLogger()`: Argument `$logger` must be of type `Psr\Log\LoggerInterface`, `Closure` given:

> ![2024-11-28 11_47_32-Window](https://github.com/user-attachments/assets/61bf2cd9-0913-42b6-b821-f15b78473055)

> ![2024-11-28 12_04_24-Window](https://github.com/user-attachments/assets/80c26f78-6dd8-4a41-8f9a-7805d0702d05)

#### Current behavior

[`LoadDataFixturesDoctrineODMCommand`](https://github.com/doctrine/DoctrineMongoDBBundle/blob/5.2.x/src/Command/LoadDataFixturesDoctrineODMCommand.php#L86) does not adher to [`\Psr\Log\LoggerAwareInterface`](https://github.com/php-fig/log/blob/master/src/LoggerAwareInterface.php#L13).

#### Expected behavior

No error.

#### How to reproduce

`$ php bin/console doctrine:mongodb:fixtures:load`

**Comment by mickverm** [comment]
This issue arose in our code base as well, when Dependabot suggested updating `doctrine/doctrine-fixtures-bundle` to 3.6.0, which transitively updated `doctrine/data-fixtures` to 2.0.0. See https://github.com/doctrine/DoctrineFixturesBundle/pull/457.

**Comment by mickverm** [comment]
@GromNaN what's the timeline on releasing this fix?
